### ISSUE TITLE
How many iterations in SnPM paired ttest are sufficient? 

### ISSUE THREAD

**Issue by AndyArg** [0todd0000/spm1dmatlab#106]
Dear Todd,
We have been using SPM with paired ttests for normally distributed data sucessfully in the past. With another set of data (9 test subjects, 20 cycles each, a total of 180 cycles with 100 nodes ) which is not normally distributed we tried to use the SnPM Version of the paired ttest an

[exampledata.zip](https://github.com/0todd0000/spm1dmatlab/files/3002500/exampledata.zip)

d receive the following error:
_Error using
spm1d.stats.nonparam.permuters.APermuter/check_iterations
(line 62)

The total number of iterations (1.532496e+54) is very large
and may cause computational problems. In the call to
"inference"...
(1) Set "iterations" to a number between 10 and 10,000, or
(2) set "force_iterations" to "true" to enable calculations
for iterations > 10,000.
NOTE: Setting "force_iterations" to "true" may require
substantial computational resources and may cause crashes. USE
WITH CAUTION._

We can manually insert a number of iterations up to 10 000 but are uncertain if we should max out the number of iterations regardless of the data.
I understand that the data effects the possible number of iterations as it increases the computational task but don not quite understand specifically how using (-1) in your example code leads to a certain amount of iterations that works fine with your example data. If you could help me out with that, than I hopefully get a grip at how many iterations will suffice in our case.
I will attach a sample data set, maybe that will help with the troubleshooting.
Thank you!
Andy
[exampledata.zip](https://github.com/0todd0000/spm1dmatlab/files/3002503/exampledata.zip)

**Comment by AndyArg** [comment]
Dear Todd,
it looks like we made a mistake in setting up the correct input data. Am I correct to assume that for our purpose  (9 test subjects, 20 cycles each,  with 100 nodes / one trial as baseline, another trial for the intervention) for applying paired ttest statistics we have to calculate the means for each subject's cycles beforehand and use these new datasets: dataset 1 (9 cycles with 100 nodes for baseline), dataset 2 ( 9 cycles with 100 nodes for intervention) as input data for the analysis?
If I do this, the non-parametric paired ttest statistics do work with the aforementioned (-1) iterations - though I still couldn't figure out why...
Regards
Andy

**Comment by 0todd0000** [comment]
Hi Andy,

If the hypothesis pertains to the population of subjects, then yes, summary statistics like the mean should be calculated within-subjects before conducting a t test. The mean is usually suitable, but if you've found that the data are not normally distributed within-subjects, then the mean may not be the best estimator of that subject's central tendency. So I'd recommend checking how well each subject's mean represents the underlying data, perhaps by running within-subject normality analysis, and/or by removing outliers prior to  computing means. If the data are non-normal then the 1D median may be better than the 1D mean.

Regarding the iterations:
Since the sample size in your original analysis is large (N=180), the total number of possible permutation iterations is extremely large (1.532496e+54), it is not feasible to run all iterations (and that's why an error is generated). Usually smaller samples are used (i.e., N=10), and for small sample sizes it becomes feasible to run all possible iterations.

As a rule of thumb:  10,000 or 100,000 iterations is usually sufficient for numerical convergence, and more than 1,000,000 should be avoided unless justified. To check for numerical convergence I'd suggest trying 10,000 iterations as you have done, but re-running the analyses 10 or more times, each time setting Matlab's random state differently, like this:

```Matlab
rng(0)
%%% run first iteration

rng(1)
%%% run second iteration

...
```

The results (i.e., the critical test statistic value) will vary numerically with the random state. If this numerical variance is small and does not affect the results qualitatively, then 10,000 iterations is sufficient.  If the variance is large and affects the results qualitatively, then try bumping up the number of iterations (to 100,000, for example) and repeating until the numerical variability in the critical threshold is small and does not affect the results qualitatively.

Todd

**Comment by mathblandeau** [comment]
Dear Todd,

I was about to ask you the same question but now I understand better the iteration parameter.
I am looking for a way to quantify numerical stability and I wanted to have your advised.
The idea is to run 10 to 30 times my nonparam SPM, extract the zstar threshold value then compute the variation coefficient (std/mean) of all zstar values.

I the VC is under 5% I consider it to be stable, would you agree with this approach ?
Best
M.

**Comment by 0todd0000** [comment]
I think that's fine but I'm not certain whether there is any theoretical justification for that particular approach as opposed to another (e.g. 100 or 100 repetitions, different VC threshold, etc.). I think it would be sufficient to judge stability in terms of the qualitative interpretation. If the qualitative interpretation of the results is unaffected, then the results can be considered to be sufficiently stable from an interpretation perspective.

**Comment by ChantyR** [comment]
Dear Todd, 

Thank you for the advice above. Similarly, for the paired t-tests I got the same error message [The total number of iterations (262144) is very large and may cause....] when I had "iterations = -1". I have now changed it to "iterations = 10000" and I just wanted to check that this number was ok to use? The code seems to run now, I just wanted to double check my results were correct. For my experiment I have two groups of tennis players (A[n=18] and B[n=22]) who hit the ball at two different spin levels. I am using the paired t-test to compare the two different spin levels within the same group (A and B).

Thank you for your help in advance

**Comment by 0todd0000** [comment]
Yes, any number is fine to use provided the results are numerically and qualitatively stable. For alpha=0.05 the minimum necessary number of iterations is 1/alpha = 20, but usually this is not sufficient to achieve stability. Often 1000 iterations is suitable, but generally 10,000 iterations is safer. Regardless, numerical and qualitative stability should be checked.
