### ISSUE TITLE
T-Test Inference Code Error

### ISSUE THREAD

**Issue by nrendos** [0todd0000/spm1dmatlab#108]
When attempting to use spm1d.stats.ttest2, there is an error running the inference code on MATLAB version 2017b. The ttest2 code runs, but the inference code does not. 

I get the following error "Undefined function or variable spm_uc'. This error has also come up as 'Undefined function or variable for type "double"' in another instance (picture of error and code attached). This code however, has worked on a friend's computer who has version 2018a. 

I have been unable to get the source code to work. I have also deleted and re-downloaded the spm source code folders with no improvement.

<img width="993" alt="Screen Shot 2019-04-04 at 3 27 27 PM" src="https://user-images.githubusercontent.com/49290760/55586370-664c6a80-56ee-11e9-8504-614687605048.png">

**Comment by nrendos** [comment]
I also get the same error with the example ex1d_ttest2.m file as well.

**Comment by 0todd0000** [comment]
Hi, that error means that Matlab can't find the "spm_uc.m" file, which is located in the ./spm1d/spm8 folder.  The easiest way to solve this problem is to add all of spm1d's subfolders to the Matlab path, as described in [**spm1d**'s Matlab installation instructions](http://www.spm1d.org/install/InstallationMatlab.html).

In those instructions it doesn't specify how to actually add folders to Matlab's path, so just in case, here are two options:

Option 1:  Use the [*addpath* and *genpath*](https://www.mathworks.com/help/matlab/ref/genpath.html) commands

Option 2:  Use the [Add with Subfolders](https://www.mathworks.com/help/matlab/matlab_env/add-remove-or-reorder-folders-on-the-search-path.html?searchHighlight=add%20path%20with%20subfolders&s_tid=doc_srchtitle) button.
