### ISSUE TITLE
Adjusted p-value for repeated t-test  - false positive risk calcuator

### ISSUE THREAD

**Issue by burniel** [0todd0000/spm1dmatlab#111]
I have read the post 'Adjusted p-value for repeated t-test #92' about Bonferonni corrections to p-value when running mutilate t-tests. I have been reading some of David Colquhoun from UCL's papers see below and investigated his calculator at http://fpr-calc.ucl.ac.uk/ to calculate the false positive risk. Have you used this method before to adjust the p-value and how does it fit with the theory behind SPM?

Colquhoun, D. (2014). An investigation of the false discovery rate and the misinterpretation of p-values. Royal Society Open Science, 1(3), 140216. 
Colquhoun, D. (2017). The reproducibility of research and the misinterpretation of p-values. Royal Society Open Science, 4(12), 171085. 
Colquhoun, D. (2019). The false positive risk: A proposal concerning what to do about p-values. The American Statistician, 73(sup1), 192-201.

**Comment by 0todd0000** [comment]
Thank you for this interesting post!  I am unfamiliar with false positive risk, but it would appear that it involves a Bayesian interpretation of p values. This perspective would be difficult to apply to SPM's cluster-specific p values because the p values are undefined for p > alpha; this might actually make Bayesian calculations impossible. It is conceivable that false positive risk could be calculated for the main result (i.e., the alpha-based critical threshold), but this threshold is asymptotic, and valid only for relatively small alpha (< 0.2), which may similarly make Bayesian calculations difficult.

Nevertheless, false discovery rate (FDR) is straightforward to apply to SPM results. We currently have a paper in preparation which compares FDR results to standard SPM results, so represents a step toward false positive risk-like interpretations.

Overall, I think the problem is negligible for SPM's cluster-specific p values, because they are less than alpha by definition, and represent simply a *post hoc*-like qualification of the main critical threshold. I also think the problem is negligible when the signal is large (i.e., large t and F values), because minor threshold adjustments will not qualitatively affect the results. The problem is certainly relevant to the threshold when the signal is small, but I think a similar perspective on the results could be achieved by applying (i) parametric inference, (ii) nonparametric inference, and (iii) FDR, and comparing the results. Currently **spm1d** supports parametric and non-parametric inference, and future versions will support FDR-based inference.
