### ISSUE TITLE
Posthoc two-way ANOVA repeated measures on one factor test

### ISSUE THREAD

**Issue by meteor77** [0todd0000/spm1dmatlab#117]
Hi Todd,

I have used the two-way ANOVA repeated measures on one factor, and the test found a significant difference for the within-subject factor. The variables are as follows:

 spmlist   = spm1d.stats.anova2onerm(Kinematic, Band, Gender, SubN);

Kinematics: knee kinematics during a squad
Band: 3 different resistance bands and 1 control
Gender: male and female
SubN: Number of subjects (23)

I was wondering how is it possible to do a posthoc test for this analysis.

I used the anova1_posthoc.m to perform the analysis, but no significant showed up for the bands.

**Comment by meteor77** [comment]
Any suggestions on this?

**Comment by 0todd0000** [comment]
Hi, sorry for the delay.  Note that **anova1_posthoc.m** uses two-sample tests (**spm1d.stats.ttest2**) for *post hoc* analyses because the design is between-subjects (i.e., not repeated measures - RM). To conduct *post hoc* analyses on Band, which is an RM factor, try  paired t tests  (**spm1d.stats.ttest_paired**). The results may not agree precisely with the ANOVA results, but they should produce closer results than two-sample tests.
