### ISSUE TITLE
Noisy SPM 

### ISSUE THREAD

**Issue by Mo1351** [0todd0000/spm1dmatlab#12]
I am not very strong on SPM method, but I used your Matlab examples (PlantarArchAngle scripts) to run my T test. The question that raised after my pairwise comparison is the noisy nature of my time series in one of my variables that is time to contact (TTC). I attached the graphs and raw data for your information and I am wondered if you can check my raw data (Tau Y spreadsheet) for accuracy of the procedure. The data is arranged so that there are 3 groups and 101 data for swing phase (%). I used SPMt to compare Tau Y between groups separately. I appreciate for any help.
[Sample - Copy.xlsx](https://github.com/0todd0000/spm1dmatlab/files/127950/Sample.-.Copy.xlsx)
![tauy g1-g2](https://cloud.githubusercontent.com/assets/17196780/13006321/22d1d688-d180-11e5-8506-5b08b4d9120d.jpg)

**Comment by 0todd0000** [comment]
Mo1351,

Thank you for your question.  In general, the SPM will be noisy like this only if the underlying data are also noisy.

Please understand that we can't look through raw data for problems in this free support forum.  If you would like us to look check your dataset thoroughly please consider contacting us privately for a consultancy.

Otherwise, please feel to attach additional details, including figures and/or scripts. In particular, to check whether these t test results make sense, please attach a figure which depicts the means and standard deviations of each group.  If the mean trajectories are noisy then the SPM will also be quite noisy.  

Regards,
Todd
