### ISSUE TITLE
Clusters outside ROI when using nonparam ANOVA

### ISSUE THREAD

**Issue by pariterre** [0todd0000/spm1dmatlab#121]
Hello!

I wanted to use non parametric 3 ways repeated-measure ANOVA. When triple interactions are present, I must fix the factors in the region of interest (ROI) that is significant. However, when I get the cluster from the resulting 2 ways ANOVA, I get clusters outside the ROI, which I think is unattended. 

I tested the same idea using a 2 ways nonparametric ANOVA and fixed factors for a ANOVA and got the same issue. Please find below the relevant code. During my test, I noticed that it doesn't seem to generate the same problem when using a parametric test. 

@pariterre and @romainmartinez

```MATLAB
clear;  
clc; 
close all;

% Setup the problem
rng(42 * 2);
iter = 50; 

% Get data from SPM1d
dataset = spm1d.data.uv1d.anova2.SPM1D_ANOVA2_3x4();
[Y,A,B] = deal(dataset.Y, dataset.A, dataset.B);

% Perform an non param ANOVA2
spmlist_2ways = spm1d.stats.nonparam.anova2(Y, A, B);
spmilist_2ways = spmlist_2ways.inference(0.05, 'iter', iter);

% Only continue if there is interaction (spoiler, I chosed the data so it does!)
if spmilist_2ways.SPMs{end}.h0reject
    % Only keep the ROI where there are clusters
    roi_2ways = zeros( 1, size(Y,2) );
    for i = 1:length(spmilist_2ways.SPMs{end}.clusters)
        span = round(spmilist_2ways.SPMs{end}.clusters{i}.endpoints+1);
        roi_2ways(span(1):span(2)) = 1;
    end

    % Keep B constant (could be A too...) 
    for j = 1:max(B)
        % Perform the ANOVA
        spmlist_1way   = spm1d.stats.nonparam.anova1(Y(B == j, :), A(B == j), 'roi', roi_2ways);
        spmilist_1way  = spmlist_1way.inference(0.05, 'iter', iter);

        % Only show things for Main effect (spoiler, it works only with j = 1)
        if spmilist_1way.h0reject
            % Get the ROI where there is Main effect
            roi_1way = zeros( 1, size(Y,2) );
            for i = 1:length(spmilist_1way.clusters)
                span = round(spmilist_1way.clusters{i}.endpoints+1);
                roi_1way(span(1):span(2)) = 1;
            end

            % Showing the problem (ROI of the Main effect should be inside
            % the ROI of the 2 ways)
            plot(roi_2ways)
            hold on
            plot(roi_1way, '--')
            legend({'ROI (Clusters from 2 ways)', 'Clusters from 1 way that are supposed to be inside ROI'})
        end
    end
end
```

**Comment by 0todd0000** [comment]
Hi, I haven't yet run the code you sent (I don't have access to Matlab at the moment) but I think I understand the problem. Here are two thoughts:

- If an ROI is defined, and a given cluster lies partially inside the ROI, and **also extends beyond the ROI**, that cluster is usually considered to be part of the ROI, by convention
- If an ROI is defined, and a given cluster lies **completely outside of the ROI**, it must be ignored because it is irrelevant to the null hypothesis

**Comment by pariterre** [comment]
Ok! Thanks for your answer! If I understand well, it means it's the intended behavior, isn't it?

**Comment by 0todd0000** [comment]
Yes, I think this describes the generally accepted perspective on ROIs and clusters.

I ran the code you sent without errors, but I noticed a potential problem:
It is generally not valid to compare two-way and one-way results.

For simple univariate 0D data, it is relatively easy to ensure that all *post hoc* analyses (e.g. t tests) agree probabilistically with the main test (e.g. one way ANOVA).  Maintaining probabilistic consistency between the main and *post hoc* tests becomes more difficult, and somewhat abstract, for multivariate 0D data. It also becomes difficult for uni-/multivariate 1D data. I am unaware of robust *post hoc* procedures in the SPM literature which maintain probabilistic consistency between the main and *post hoc* tests.

Since **spm1d** does not not  support robust *post hoc* analysis, it's usually best to regard the main test's outputs as the main results, and arbitrary *post hoc* analyses as approximate qualifications of that main result.
