### ISSUE TITLE
How to define the factors (A, B, C) in ANOVA3

### ISSUE THREAD

**Issue by milaaadz** [0todd0000/spm1dmatlab#126]
Hi,

I have a set of data for 70 subjects that they walked on 4 different surfaces. We are going to look at the effects of the walking surface (4), arch index (3), gender (2) and age (2, young and old). I was wondering if the correct method to test it is to use ANOVA3? (spm1d.stats.anova3)

I have looked at the example (SPM_1D/examples/stats1d/ex1d_anova3), but it's not clear how the factors were defined. When I changed the A, B, and C, the code complains that Design must be balanced. 

Is there any other example that I can use to learn about the test?

Is this test appropriate for this study?

Regards,
Milad

**Comment by 0todd0000** [comment]
Hello Milad,

I think there are two problems:

Problem 1:  **4-way design**
* It sounds like there are four experimental factors (surface, arch, gender, age), and thus that this is a 4-way design.
* **spm1d** currently only supports up-to 3-way designs. **spm1d.stats.anova3** and all other procedures named **anova3**... refer to 3-way designs. There are no **anova4**... or higher-order procedures in **spm1d**.

Problem 2:  **balance**
* **spm1d** currently only supports balanced designs, which means that the same number of observations must be present in all condition combinations.
* Since there are 48 condition combinations (4 surface x 3 index x 2 gender x 2 age), there must be a total of 48*n* subjects yield balance, where *n* is the number of subjects in each condition combination, and *n* > 1.  Thus there must be a minimum of 96 subjects for a balanced 4-way design.

Possible solutions to these problems:

* As a preliminary analysis I'd suggest the following:
    * Pool factor levels to create a simplified design, then reduce the number of subjects to impose balance.
    * One option is to pool the genders, thereby creating a 3-way design with 24 conditions (4 surface, 3 arch, 2 age). In this case you should reduce the total number of subjects to 48 so that there are 2 subjects for each condition.
    * Another option is to pool both age and gender, thereby creating a 2-way design with 12 conditions (4 surface, 3 arch). In this case you should reduce the total number of subjects to 60 so that there are 5 subjects for each condition.
   * Note that these are just preliminary analyses that would allow you to obtain results from **spm1d**;  I would not recommend arbitrarily reducing the number of subjects if you intend to publish the results.

* If you need to use all subjects' data, and only the existing dataset, please first try analyzing 0D data (e.g. the maximum value in time) using a software package that supports arbitrary m-way ANOVA. Two examples are: SPSS and R. If you are unable to analyze 0D data using those packages, it will be impossible to analyzed 1D in **spm1d**.  I suspect that there is insufficient data to support the current m-way design, but analysis in SPSS, R or another package will confirm this suspicion.

Todd

**Comment by milaaadz** [comment]
Hi Todd,

Thank you for quick response. That was really helpful.

**Comment by milaaadz** [comment]
Hi Todd,

I have a follow up question about this topic.

So we decided to reduce the factors to 3 which would be age (2), sex (2) and walking surfaces (4). I understand that we need 16n subjects (n>1) in each condition. But the condition is not clear to me. Does that mean we need at least 16 subjects that are young, female on walking surface number 1? Then again another 16 young, male on walking surface number 1?

**Comment by 0todd0000** [comment]
*Short answer*: yes, but only if it is a between-subjects design (i.e., **spm1d.stats.anova3**).

*Longer answer*: To achieve balance, the same number of subjects should appear in each cell, where a "cell" is one combination of all factors, like the combinations you mention. Subjects can be repeated across cells, in which case it would be a within-subjects (i.e., repeated measures) design. If subjects are not repeated across cells, it is a between-subjects design (i.e., **spm1d.stats.anova3**). If it is a between-subjects design, then yes: 16*n* subjects are required to achieve balance. Subject numbers can be reduced by adopting a within-subjects design, and **spm1d** supports a variety of within-subjects designs for three-way ANOVA (e.g. **spm1d.stats.anova3onerm**).  For example, 12 subjects may be sufficient if all subjects are measured for all walking surfaces. Note that the "48*n*" suggestion above pertains to a four-way between-subjects design.

In my previous response (on 11 June) I didn't consider within-subjects designs, because I was thinking only of **spm1d.stats.anova3**. I'm very sorry if this was unclear.

**Comment by milaaadz** [comment]
Thanks again Todd. I really appreciate your time.

Subjects repeat across the cells in this case. The same subjects walk on 4 different walking surfaces. But then I divide them by age and sex. 

One last question, do I need to correct the p-value for the multiples comparisons? Would that be 0.05/(16x(number of subjects in each condition))?

Regards,
Milad

**Comment by 0todd0000** [comment]
Yes, p values need to be corrected for *post hoc* analysis. Please see:
https://spm1d.org/doc/PostHoc/anova.html

Please also see:
https://github.com/0todd0000/spm1d/issues/22
https://github.com/0todd0000/spm1d/issues/6
and search the **spm1d** forums for "post hoc" where you'll find a number of relevant discussions.

You may also want to try the "Factorial" add-on:
https://spm1d.org/Addons.html
