### ISSUE TITLE
the difference between ttest and ttest2 to identify side-to-side differences

### ISSUE THREAD

**Issue by milaaadz** [0todd0000/spm1dmatlab#128]
Hi,

I have some pressure data for for left and right feet for 80 subjects. I want to see if there is any differences between the sides.
So I was wondering which test would fit best? Should I use ttest2 to identify the differences between the sides (L and R), or should I use ttest to see if the absolute side-to-side differences are different from 0?

A) spm  = spm1d.stats.ttest2(Left, Right);

B) SSD = abs(Left - Right); mu = 0;    spm  = spm1d.stats.ttest(SSD - mu);

Is it safe to assume that I should get the same results if I use the both tests? 

Thanks,

**Comment by 0todd0000** [comment]
If you change **ttest2** to **ttest_paired**, then yes: you should get the same results.

A paired t test is equivalent to a one-sample test on the paired differences. Two-sample tests consider only group means, and not paired differences, and are not equivalent to one-sample tests.

Consider the dataset:

Condition A:  [100,  140,  180,  150,  210]
Condition B:  [150,  191,  231,  195,  265]

* Two-sample test results: t = 1.871, p=0.098
* Paired test results:  t = 31.500, p = <0.001

The paired test has a high t value (i.e., a strong effect) because the paired differences are all close to 50:

* Paired differences = [50, 51, 51, 45, 55]

The two-sample test has a much smaller t value because the within-condition variability is very large relative to the between-condition mean difference.

**Comment by milaaadz** [comment]
Thanks a lot Todd. I appreciate your time.

That's right, **ttest_paired** returns the same answer as **ttest** does, only if there is no absolute values. SSD should be SSD = Left-Right, not SSD = abs(Left-Right); 

Thank you!
