### ISSUE TITLE
Non-parametric 3-way rm anova test: design questions

### ISSUE THREAD

**Issue by Freshtea1** [0todd0000/spm1dmatlab#136]
Dear All,  Dear Todd,

Thank you very much for providing this powerful toolbox.
I want to run a non-parametric ANOVA on my partly non-normally distributed data. I have encountered several issues and I hope its okay to summarize them here. I am more than happy to create new issues for each of them if necessary.

I am comparing SCI patients (n=12) with controls (n=12) (independent factor, with 2 levels). I have two locomotor conditions/tasks which both groups are performing (independent factor, C1 and C2, 2 levels). The center of mass (COM, dependent variable, 3 levels) is my continuous variable. It has 3 levels since I am interested in the influence of the axes (independent factor, Medio-lateral x, anterior-posterior y, and vertical z direction).
In summary, I have the factors: 
- population: SCI vs. Controls (2 levels, 24 subjects) -> categorial: 0,1
- locomotor condition: C1 and C2 (2 levels) -> categorial: 0,1
- Axes: x,y,z direction (3 levels  for 2 conditions) -> categorial: 0,1,2

Thus, in the end I have 12x3x2 rows per population group, so 72 rows for SCI and 72 rows for controls)
with the dependent factor Y (matrix of size 144x100 = COM in x,y,z direction) and Subject vector (144x1).
I have decided on the function spm1d.stats.nonparam.anova3onerm because I am interested in whether there is an effect  of population, locomotor task and type of COM axis.

First question: is 'spm1d.stats.nonparam.anova3onerm' the right one to use?

Second question: Is it valid to leave the locomotor condition factor in? My problem is that I get the warning "Warning: Only one observation per subject found. [...]". this warning has been discussed in this forum already but I'm still not sure whether this has something to do with the way I am designing the ANOVA/parameters. Because for each subject I have two conditions and 3 COM movements... so I would have expected 2 observations per subject.

Third question: with so many parameters and comparisons, which _post hoc_ test would you recommend? 
Maybe it makes sense to take the difference Control_n(C2-C1) and SCI_n(C2-C1) (in the x,y,z direction) and calculate a  non-parametric t-test (normal, not paired, since we have different groups, I guess). 
If I interpret the results of the anova (below) correctly, they suggest that there is an effect of population (=A), meaning that  the groups differ but there is no interaction between population and condition and population and Axes, is this correct? I am not really sure what this means.
![results_3wayanovaonerm](https://user-images.githubusercontent.com/77054214/103770160-d5729380-5025-11eb-89da-e777f2d7d3f3.png)

SnPM{F} inference list (1D)
   design    : ANOVA3onerm
   nEffects  : 7
   nPermUnique  : 5.550294e+249
   nPermActual  : 10000
Effects:
     A     F = (1x503) array    h0reject = 1
     B     F = (1x503) array    h0reject = 1
     C     F = (1x503) array    h0reject = 1
    AB     F = (1x503) array    h0reject = 0
    AC     F = (1x503) array    h0reject = 0
    BC     F = (1x503) array    h0reject = 1
   ABC     F = (1x503) array    h0reject = 0

Thanks a lot,
Freshi

Function I have used:
FFn   = **spm1d.stats.nonparam.anova3onerm**(Y,pop, cond, Axes,SBJ);
alpha      = 0.05;
iterations = 10000;
FFni       = FFn.inference(alpha, 'iterations', iterations);
disp_summ(FFni)
close all

**Comment by 0todd0000** [comment]
> First question: is 'spm1d.stats.nonparam.anova3onerm' the right one to use?

A yes/no answer is difficult here, but I'm leaning toward "no"...

A correct answer would depend on what "Axes" means in relation to the dependent variable (DV). If the DV is COM position or COM velocity, or another 3-component vector, then the DV is multivariate, and AXES is actually part of the DV, and not an experimentally manipulated parameter. In this case a multivariate procedure like MANOVA would be more appropriate. Unfortunately **spm1d** only supports one-way MANOVA at the moment.

If the DV is indeed univariate, then I believe **anova3tworm** may be more appropriate than **anova3onerm**, provided a single subject was involved in all levels of both CONDITION and AXES.


> Second question: Is it valid to leave the locomotor condition factor in? My problem is that I get the warning "Warning: Only one observation per subject found. [...]". this warning has been discussed in this forum already but I'm still not sure whether this has something to do with the way I am designing the ANOVA/parameters. Because for each subject I have two conditions and 3 COM movements... so I would have expected 2 observations per subject.

I cannot say whether it is valid to model Condition, because validity in this case depends on how the experiment was designed and executed. Assuming that Condition has indeed been modeled in a valid manner, you can ignore the warning. "Observations per subject" refers to the number of times a single subject is represented in each ANOVA cell, where a 'cell' is specific combination of all factors.


> Third question: with so many parameters and comparisons, which post hoc test would you recommend?

Post hoc tests are not yet formally supported in **spm1d**, so the only recommendation  I can give is to regard the ANOVA results as the main results, and all other analyses as complimentary attempts to explain those results.  As a general rule, note that no post hoc analysis should refute the main ANOVA results;  if it does, then it was conducted incorrectly. As a first approximation, use a Bonferroni correction across all post hoc possibilities. This is a conservative approach, but a useful first approximation.  Unfortunately three-way and higher-order designs are highly complex, and much less powerful than simpler designs, and their results are difficult to explain without detailed post hoc considerations. Multivariate DVs make post hoc analyses even more complex, and generally do not relate directly to a pre-defined coordinate system like (ML, AP, vertical).

**Comment by Freshtea1** [comment]
Thank your for your prompt and detailed answer.

Indeed, DV is the COM position (in ML, AP, and vertical direction), and therefore multivariate, as you said. 
I will try to keep it more simple ...

Many thanks,
Freshi
