### ISSUE TITLE
Interpretation of Hotelling test results for 1D data

### ISSUE THREAD

**Issue by fmoissenet** [0todd0000/spm1dmatlab#14]
Dear Todd Pataky,

We are using spm1d for analysing kinematics during gait.
The results we obtained present significant differences during a large portion of the gait cycle, while the post-hoc analysis does not reveal any significancy on kinematic parameters.
We are thus wondering if it could be true to justify a "sum" of the effect observed on parameters to explain the covariance? In other words, when several parameters are near the threshold during t tests, can we imagine that the sum of these effetcs is enough to considere that the differences observed with Hotelling test are related to?

Thank you for exchanging about this interpretation issue.

Florent Moissenet.

**Comment by 0todd0000** [comment]
Dear Florent,

Regarding a Hotelling's T2 result as a sum of t effects is approximately correct, but it would be slightly more accurate to regard it as a directional sum.  As depicted in the figure below, a two-sample  Hotelling's T2 statistic embodies both (a) the mean difference vector (ΔF), and (b) variance in the direction of ΔF.  In this case the T2 effect is large because the variance is small in the direction of ΔF.  The individual univariate effects (ΔFx and ΔFy) are smaller because the variance is larger in the X and Y directions . 

Post hoc results which use an a priori XYZ coordinate system will therefore frequently be weaker than T2 results.  Moreover they will agree with the T2 result only if the effect happens to be parallel to one of the coordinate axes. More generally, obtaining agreement between post hoc analyses and the main Hotelling's T2 test requires one to rotate the coordinate system.  We intend to implement such procedures in future versions of **spm1d**.

Regards,

Todd


![ex_hotellings](https://cloud.githubusercontent.com/assets/4276626/13445896/721b86ae-e052-11e5-935c-c280f21fcde2.png)

**Comment by fmoissenet** [comment]
Thank you for this really clear explanation!
Best regards,
Florent.


Le 02/03/2016 00:56, Todd Pataky a écrit :
>
> Post hoc results which use an a priori XYZ coordinate system will 
> therefore frequently be weaker than T2 results. Moreover they will 
> agree with the T2 result only if the effect happens to be parallel to 
> one of the coordinate axes. More generally, obtaining agreement 
> between post hoc analyses and the main Hotelling's T2 test requires 
> one to rotate the coordinate system. We intend to implement such 
> procedures in future versions of *spm1d*.
>

-- 

*Florent MOISSENET*

Ingénieur en Biomécanique (PhD)

/REHAZENTER - Centre National de Rééducation //Fonctionnelle et de 
Réadaptation /

/1 rue André Vésale, L-2674 Luxembourg +352 2698 94310 Pour sauver des 
arbres, mangez des castors et n’imprimez pas cet e-mail !/
