### ISSUE TITLE
2way ANOVA Post hoc design

### ISSUE THREAD

**Issue by jinhee615** [0todd0000/spm1dmatlab#144]
Hello.

I designed 3x3 (group x condition) two-way ANOVA with 60 subjects. 

Control / Patients A / Patients B, and Gait Condition 1 2 3.

So I made a code like 
spm=spm1d.stats.anova2(Dataset Y, subjects, conditions); %
spmi = spm.inference(0.05);

And Group main effect and interaction were observed.
What kind of Post hoc would be appropriate? can I run it with SPM?

**Comment by 0todd0000** [comment]
> spm=spm1d.stats.anova2(Dataset Y, subjects, conditions);

If the subjects performed all conditions, then this may actually be a repeated measures (RM) design, in which case the relevant test would be:

```
spm=spm1d.stats.anova2onerm(y, GROUP, CONDITION, SUBJECT);
```

Please refer to the examples in `./spm1dmatlab/examples/stats0d/ex_anova2onerm.m` to check whether your design is indeed an RM design.

> What kind of Post hoc would be appropriate? can I run it with SPM?

Post hoc t tests and/or paired t tests are usually appropriate, depending on the type of ANOVA. There is a Matlab addon for  **spm1d** called "fctSPM" that helps to automate post hoc tests. Please refer to [spm1d addons](https://spm1d.org/Addons.html).


Additionally, searches for "post hoc" in the [spm1d MATLAB forum](https://github.com/0todd0000/spm1dmatlab/issues?q=%22post+hoc%22) and [main spm1d forum](https://github.com/0todd0000/spm1d/issues?q=%22post+hoc%22) will return a number of relevant issues including:

* https://github.com/0todd0000/spm1dmatlab/issues/74
* https://github.com/0todd0000/spm1dmatlab/issues/98
* https://github.com/0todd0000/spm1dmatlab/issues/127
* https://github.com/0todd0000/spm1d/issues/3
* https://github.com/0todd0000/spm1d/issues/38
* https://github.com/0todd0000/spm1d/issues/39
* https://github.com/0todd0000/spm1d/issues/148

**Comment by jinhee615** [comment]
Thank You for your answer! Now I'm trying to adapt "fctSPM" in two-way ANOVA design.


I have one more question.
I have another design : Comparison of 3 Group's gait conditions.

Group A (n=15), B(n=20), C(n=14). 
Dataset of Each Group named YA, YB, YC each.

I constructed code as

spm=spm1d.stats.anova1(Y, subj)
and if there is a significant difference with those three Groups. 


posthoc1=spm1d.stats.ttest2(YA,YB)
posthoc2=spm1d.stats.ttest2(YB,YC)
posthoc3=spm1d.stats.ttest2(YA,YC)

posthoc1i=posthoc1.inference(0.05)
posthoc2i=posthoc2.inference(0.05)
posthoc3i=posthoc3.inference(0.05)


I made a code like above to run post hoc.

ttest2 is appropriate for one way anova post-hoc? or ttest would be fit more? if latter one is better, may I ask how to build code? (I couldn't understand when I refered example.)

**Comment by 0todd0000** [comment]
This is partially correct, but there is a problem:
Before conducting post hoc tests you should divide the groups further into `YA1`, `YA2`, `YA3`, `YB1`, ... 

Since **spm1d** does not officially support *post hoc* analyses, please consider asking these questions in the [fctSPM](https://github.com/tramarobin/fctSPM) forum;  fctSPM officially supports *post hoc* analyses, and I expect that the fctSPM developers would be happy to help.

**Comment by jinhee615** [comment]
Thank You for your answer. But Can I get more detail?

Group A, B, C, and each of data is YA, YB, YC.

Y=[YA; YB; YC].  <-Y is total dataset.

to perform ttest2, Should I divide groups more as you said YA1, YA2, YA3 ... ?

**Comment by 0todd0000** [comment]
As a 2x3 example, see the figure below which appears at [this link](https://statistics.laerd.com/spss-tutorials/two-way-anova-using-spss-statistics-2.php). Note that there are 6 separate group means.

For your 3x3 design, 9 separate groups are needed for *post hoc* comparisons. You will also need to use both **ttest2** (for between-subjects comparisons) and **ttest_paired** (for within subjects comparisons).

Since **spm1d** does not officially support *post hoc* analyses I am now closing this issue. Please direct additional questions to the fctSPM forum or elsewhere.

![](https://statistics.laerd.com/spss-tutorials/img/twa/two-way-anova-output-5.png)
