### ISSUE TITLE
nonzero-standard deviation check in MATLAB toolbox

### ISSUE THREAD

**Issue by fjonca** [0todd0000/spm1dmatlab#167]
Dear Pr. Pataky,

I am contacting you about Matlab toolbox and its latest update with the add of the nonzero-standard deviation check. 

For my research project, I want to compare simulated data to their siblings from experiment. To do this, I choose to use SPM method to compare both corridors thanks to the spm1dmatlab toolbox you are developing.

With a first version from the git repository compare numerical and experimental signals. In these data, numerical signals have no variabilities (especially before and after impact). However with the  latest update, I cannot launch my comparison anymore without an error.

- Is this nonzero-standard deviation control necessary for a proper statistical comparison regarding the theory used?
- If no, for my application, can I still use the former version without this evaluation or should I use the Python version? I have seen that there is the possiblity to have standard deviation close to 0 with the addition of eps value.
- If I shall use new version, have you got pieces of advice to conduct an analysis without errors?

Thanks in advance for your answers.
Your faithfully,

François Jonca

**Comment by 0todd0000** [comment]
Thank you for this question and apologies for the new functionality confusion!

In general, you must pre-process the data so that only the temporal regions you want to analyse are included in the data you submit to an **spm1d** routine. If you are analyzing impacts, for example, it is possible to record data before and after impact for 1 s, 5 s, 10 s, 1000 s, etc. If you include these non-impact regions in your submitted data **spm1d** will assume that you want to analyze those regions. Note that SPM results are generally affected by the length of the data.



<br>

> Is this nonzero-standard deviation control necessary for a proper statistical comparison regarding the theory used?

Yes. Zero variance cannot be statistically analyzed. Zero variance regions must be excluded from the dataset.

<br>

> If no, for my application, can I still use the former version without this evaluation or should I use the Python version? I have seen that there is the possiblity to have standard deviation close to 0 with the addition of eps value.

Please use the most recent version.

<br>

> If I shall use new version, have you got pieces of advice to conduct an analysis without errors?

Please remove all zero-variance regions you do not want to analyze before submitting to **spm1d** analysis. This is known as [segmentation](https://en.wikipedia.org/wiki/Image_segmentation);  both segmentation and [registration](https://en.wikipedia.org/wiki/Image_registration) (i.e., "temporal normalization") must be conducted before analyzing data. Neither segmentation nor registration is directly supported in the current version of **spm1d**.
