### ISSUE TITLE
ANOVA test significant while the post hoc test is not significant.

### ISSUE THREAD

**Issue by 0todd0000** [0todd0000/spm1dmatlab#169]
This issue is continued from:
https://github.com/0todd0000/spm1d/issues/220

**Comment by 0todd0000** [comment]
Code copied below:

<br>
<br>


**ANOVA code**

```octave
clc
Musc_Act= 'C:\Users\shivangi.000\Desktop\muscle_activations.xlsx';
%
%For 1st Model and all three gravities
GasLat_1stModel_1stGravity = xlsread(Musc_Act,1);
P = GasLat_1stModel_1stGravity(2:end,1:end);
GasLat_1stModel_2ndGravity = xlsread(Musc_Act,3);
Q = GasLat_1stModel_2ndGravity(2:end,1:end);
GasLat_1stModel_3rdGravity = xlsread(Musc_Act,5);
R = GasLat_1stModel_3rdGravity(2:end,1:end);
n0 = size(P, 1); %number of group 0 observations
n1 = size(Q, 1); %number of group 1 observations
n2 = size(R, 1); %number of group 2 observations
b0 = 0 * ones(n0, 1); %group 0 labels
b1 = 1 * ones(n1, 1); %group 1 labels
b2 = 2 * ones(n2, 1); %group 2 labels

%For 2nd Model and all three gravities
GasLat_2ndModel_1stGravity = xlsread(Musc_Act,2);
J = GasLat_2ndModel_1stGravity(2:end,1:end);
GasLat_2ndModel_2ndGravity = xlsread(Musc_Act,4);
K = GasLat_2ndModel_2ndGravity(2:end,1:end);
GasLat_2ndModel_3rdGravity = xlsread(Musc_Act,6);
L = GasLat_2ndModel_3rdGravity(2:end,1:end);
n3 = size(J, 1); %number of group 0 observations
n4 = size(K, 1); %number of group 1 observations
n5 = size(L, 1); %number of group 2 observations
b3 = 0 * ones(n3, 1); %group 0 labels
b4 = 1 * ones(n4, 1); %group 1 labels
b5 = 2 * ones(n5, 1); %group 2 labels

M = [P;Q;R]; %all data from model 1 for 10 subjects
n6 = size(M, 1);
Y = [J;K;L]; %all data from model 2 for 10 subjects
n7 = size(Y, 1);
a0 = 0* ones(n6,1);
a1 = 1* ones(n7,1);
A= [a0;a1]'; % Factor 1 which indicates the number of model types i.e 2
Z = [M;Y];
B = [b0; b1; b2; b3; b4; b5]'; % Factor 2 which indicates the number of gravities i.e 3

SUBJ = [1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10];

%spm_bs = spm1d.stats.anova1(M, A); %between-subjects model
spmlist = spm1d.stats.anova2rm(Z, A, B, SUBJ);
spmilist = spmlist.inference(0.05);
spmilist.plot('plot_threshold_label',true, 'plot_p_values',true, 'autoset_ylim',true);
```

<br>
<br>
<br>

**Post-Hoc test code**

```octave
clc

Musc_Act= 'C:\Users\shivangi.000\Desktop\muscle_activations.xlsx';

%For 1st Model and all three gravities
GasLat_1stModel_1stGravity = xlsread(Musc_Act,1);
P = GasLat_1stModel_1stGravity(2:end,1:end);
GasLat_1stModel_2ndGravity = xlsread(Musc_Act,3);
Q = GasLat_1stModel_2ndGravity(2:end,1:end);
GasLat_1stModel_3rdGravity = xlsread(Musc_Act,5);
R = GasLat_1stModel_3rdGravity(2:end,1:end);

%(1) Conduct SPM analysis:
t21 = spm1d.stats.ttest_paired(Q, P);
t32 = spm1d.stats.ttest_paired(R, Q);
t31 = spm1d.stats.ttest_paired(R, P);
% inference:
alpha = 0.05;
nTests = 3;
p_critical = spm1d.util.p_critical_bonf(alpha, nTests);
t21i = t21.inference(p_critical, 'two_tailed',true);
t32i = t32.inference(p_critical, 'two_tailed',true);
t31i = t31.inference(p_critical, 'two_tailed',true);

subplot(221); t21i.plot(); title('2ndGravity - 1stGravity')
subplot(222); t32i.plot(); title('3rdGravity - 2ndGravity')
subplot(223); t31i.plot(); title('3rdGravity - 1stGravity')
```

**Comment by 0todd0000** [comment]
One initial thought is that there are more than three *post hoc* tests possible for a 2x3 ANOVA, so this code does not represent all possible *post hoc* comparisons. It appears that this code considers the main effect of factor `B`, but this is not perfectly clear because the data are reconstructed after the ANOVA is conducted (i.e., it is possible that a coding error has caused different data to be submitted to the *post hoc* tests). I therefore have the following suggestions...


Please simplify the code as follows:

- At the stage where you have defined all of the following variables: `Z`, `A`, `B`, `SUBJ`, please save these in a .mat file, then remove all previous code; this will eliminate more than 40 lines of code and will allow us to focus in on the problem
- Please make your *post hoc* analysis use the variables  `Z`, `A`, `B`, `SUBJ`;  when both the main analysis and *post hoc* tests start with the same variables it will become considerably easier to find the source of the problem

**Comment by Shivangi2208** [comment]
Hello Todd,
I saved the Z, A, B, SUBJ variables in a mat file named 'dataset'. I used this mat file to run post-hoc tests. I see what you meant by having more than 3 post-hoc tests because now considering all the combinations between the A and B factors, I have 15 pairs.
Please have a look at the code below
clc

S= load('dataset.mat');
[Y,A,B] = deal(S.Z, S.A, S.B);
%%% separate into groups:
Y00         = Y(A==0&B==0,:);
Y01         = Y(A==0&B==1,:);
Y02         = Y(A==0&B==2,:);
Y10        = Y(A==1&B==0,:);
Y11         = Y(A==1&B==1,:);
Y12         = Y(A==1&B==2,:);

%(1) Conduct SPM analysis:
t00_01        = spm1d.stats.ttest2(Y00, Y01);
t00_02        = spm1d.stats.ttest2(Y00, Y02);
t00_10        = spm1d.stats.ttest2(Y00, Y10);
t00_11       = spm1d.stats.ttest2(Y00, Y11);
t00_12       = spm1d.stats.ttest2(Y00, Y12);
t01_02       = spm1d.stats.ttest2(Y01, Y02);
t01_10        = spm1d.stats.ttest2(Y01, Y10);
t01_11        = spm1d.stats.ttest2(Y01, Y11);
t01_12        = spm1d.stats.ttest2(Y01, Y12);
t02_10       = spm1d.stats.ttest2(Y02, Y10);
t02_11       = spm1d.stats.ttest2(Y02, Y11);
t02_12       = spm1d.stats.ttest2(Y02, Y12);
t10_11       = spm1d.stats.ttest2(Y10, Y11);
t10_12       = spm1d.stats.ttest2(Y10, Y12);
t11_12        = spm1d.stats.ttest2(Y11, Y12);

% inference:
alpha      = 0.05;
nTests     = 15;
p_critical = spm1d.util.p_critical_bonf(alpha, nTests);
t00_01i       = t00_01.inference(p_critical, 'two_tailed',true);
t00_02i       = t00_02.inference(p_critical, 'two_tailed',true);
t00_10i       = t00_10.inference(p_critical, 'two_tailed',true);
t00_11i       = t00_11.inference(p_critical, 'two_tailed',true);
t00_12i       = t00_12.inference(p_critical, 'two_tailed',true);
t01_02i       = t01_02.inference(p_critical, 'two_tailed',true);
t01_10i       = t01_10.inference(p_critical, 'two_tailed',true);
t01_11i       = t01_11.inference(p_critical, 'two_tailed',true);
t01_12i       = t01_12.inference(p_critical, 'two_tailed',true);
t02_10i       = t02_10.inference(p_critical, 'two_tailed',true);
t02_11i       = t02_11.inference(p_critical, 'two_tailed',true);
t02_12i       = t02_12.inference(p_critical, 'two_tailed',true);
t10_11i       = t10_11.inference(p_critical, 'two_tailed',true);
t10_12i       = t10_12.inference(p_critical, 'two_tailed',true);
t11_12i       = t11_12.inference(p_critical, 'two_tailed',true);

close all
subplot(15,3,1);  t00_01i.plot();    title('A=0,B=0 with A=0,B=1')
subplot(15,3,2);  t00_02i.plot();   title('A=0,B=0 with A=0,B=2')
subplot(15,3,3);  t00_10i.plot();    title('A=0,B=0 with A=1,B=0')
subplot(15,3,4);  t00_11i.plot();    title('A=0,B=0 with A=1,B=1')
subplot(15,3,5);  t00_12i.plot();   title('A=0,B=0 with A=1,B=2')
subplot(15,3,6);  t01_02i.plot();    title('A=0,B=1 with A=0,B=2')
subplot(15,3,7);  t01_10i.plot();    title('A=0,B=1 with A=1,B=0')
subplot(15,3,8);  t01_11i.plot();   title('A=0,B=1 with A=1,B=1')
subplot(15,3,9);  t01_12i.plot();    title('A=0,B=1 with A=1,B=2')
subplot(15,3,10);  t02_10i.plot();    title('A=0,B=2 with A=1,B=0')
subplot(15,3,11);  t02_11i.plot();   title('A=0,B=2 with A=1,B=1')
subplot(15,3,12);  t02_12i.plot();    title('A=0,B=2 with A=1,B=2')
subplot(15,3,13);  t10_11i.plot();    title('A=1,B=0 with A=1,B=1')
subplot(15,3,14);  t10_12i.plot();   title('A=1,B=0 with A=1,B=2')
subplot(15,3,15);  t11_12i.plot();    title('A=1,B=1 with A=1,B=2')

The titles of the plots indicate the factors' combination for paired t-tests. This code generated the figure attached.
![new_post-hoc_test_result](https://user-images.githubusercontent.com/76727338/172703337-f5f9dbaa-a3e7-4b15-916d-03f1f02d1bce.jpg)

As you can see, I do not get any significance for any pair. What am I doing wrong? Please suggest.


Regards,
Shivangi

**Comment by 0todd0000** [comment]
Thank you for the code update, everything looks good with one minor exception: if the main analysis is `spm1d.stats.anova2rm`, then the post hoc analyses should use `spm1d.stats.ttest_paired`.

Regardless, you'll see in the `(A=0,B=0)` vs. `(A=1,B=2)` comparison, for example, that the absolute t-value is relatively large both near time=40% and time=60%, and that these times roughly correspond to the main effects depicted in the [ANOVA results](https://github.com/0todd0000/spm1d/issues/220).  To me this represents relatively good agreement between the *post hoc* analysis and the main ANOVA results.

Please note that it is may not be possible to achieve exact probabilistic agreement between ANOVA and *post hoc* results. Achieving precise agreement is relatively easy for 0D data, but for 1D data there are several complications including especially smoothness: the smoothness of the entire dataset (i.e., data submitted to ANOVA) is not necessarily the same as a subset submitted to a *post hoc* test. Since smoothness affects the critical t-value (and critical F-value) it is generally not possible to achieve exact agreement between ANOVA and *post hoc* analyses **unless** one both (a) forces the *post hoc* analyses to use the same smoothness as the main ANOVA, and (b) accounts for several other potential inconsistencies.

It may indeed be possible to develop a robust, automated procedure that achieves exact agreement between ANOVA and *post hoc* results. However, it is also considerably more general and also in my statistically responsible to acknowledge the fact that *post hoc* analyses are simply that:  secondary analyses that are meant to explain the main ANOVA results. If you regard *post hoc* analyses in this manner then they needn't agree precisely with the main results. Conversely, if the key experimental outcome is actually a specific comparison like  `(A=0,B=0)` vs. `(A=1,B=2)`, then the experiment should be designed to focus on that comparison.

**Comment by Shivangi2208** [comment]
Thank you for reviewing my code and providing helpful suggestions. I will perform the post-hoc analyses for the other muscles in a similar fashion and check them with ANOVA test results.
Thank you again.

Regards,
Shivangi Giri
