### ISSUE TITLE
post hoc for repeated measure anova

### ISSUE THREAD

**Issue by AfshinDk** [0todd0000/spm1dmatlab#17]
Hi,

There is a post-hoc procedure for anova1 in the SPM toolbox.
As far as I follow the code, the post hoc analysis to make a pairwise comparison between the levels of a factor is done through a Bonferroni correction. Are the other methods of post-hoc analysis (e.g. Tukey, SNK) applicable here as well?
I was wondering whether a similar approach can be used for a post-hoc analysis for the within-subject factor in a repeated measure anova? What about the interaction between the between- and within-subject factors?

Afshin

**Comment by 0todd0000** [comment]
Hi Afshin,

Thank you for your questions.  Post hoc methods other than the Bonferroni method are indeed applicable, but they're not yet available in **spm1d**.  They are on our list of feature requests that we hope to have available in the next major release of **spm1d**:
https://github.com/0todd0000/spm1d/issues/45
 
To preface the rest of this response:  all procedures (ANOVA and post hoc) that can be applied to univariate and multivariate 0D data can also be applied to univariate and multivariate 1D data.  Thus if you've seen a particular post hoc technique elsewhere (e.g. SPSS's Tukey procedure for one-way ANOVA and 0D data) then the same technique can applied to 1D data.  

Post hoc analyses can indeed be conducted for within-subjects models.  For one-way within-subjects models post hoc tests are simply paired t tests, and there is no interaction.  For two- and three-way repeated-measures models there are some post hoc procedures available in standard statistics packages like SPSS and R but as far as I know there are not very many standard options available for doing explicit post hoc tests with these complex designs, partly because the interactions coupled with within-subjects factors make things quite difficult to interpret.

Interactions between within-subject factors and between-subject factors are given in the ANOVA output, and you should be able to interpret the interaction using means. For example, in two-way ANOVA with one within- and one between-subjects factor the interaction is:

```python
>>  spmlist  = spm1d.stats.anova2onerm(Y, A, B, SUBJ);
>>  mainA    = spmlist.SPMs{1};
>>  mainB    = spmlist.SPMs{2};
>>  interAB  = spmlist.SPMs{3};
```

From the *interAB* result and plotting means for all levels of factors A and B it should be possible to interpret the interaction, but running an explicit post hoc test is trickier.

If there is a specific post hoc procedure for two- or three-way designs that you would like to see available in **spm1d** please do let us know and we'll add it to our list of post hoc procedures to implement.

Cheers,

Todd
