### ISSUE TITLE
Missing data - 3way ANOVA

### ISSUE THREAD

**Issue by freddybrown1984** [0todd0000/spm1dmatlab#177]
Hi Todd - Me again!

After your generous help with my 3-way spm ANOVA, I ran the code and obtained some results. However, after a final check of all of my data, I've discovered that one of my participants is missing a data-point (1 x 101 time series points), as I saved over one set of jumps with another so I have a perfect replication. So...

Will the SPM "work" with a missing data-point? If I remove the data to keep the number of lines/data-points constant and the design balanced, Matlab turns these into zeros (as opposed to SPSS/excel etc., where it is clear there is a missing value). Is the ANOVA therefore assuming that there IS data here, just that it's all equal to zero? Or that there's data missing? The original output:
![3wayF-25](https://user-images.githubusercontent.com/112722736/198827672-c7ba28fb-fc95-4d42-8c95-e2b331a3692e.jpg)
is now similar, but differs RE significance, compared to the new output:
![F3way1setmissing](https://user-images.githubusercontent.com/112722736/198827704-5aafaff9-4611-42d9-b062-793c0a25fa14.jpg)

As always, your help is massively appreciated. Thanks,
Freddy

**Comment by 0todd0000** [comment]
> Will the SPM "work" with a missing data-point? 

Yes, in general, but the appropriate approach depends on what is missing. In this case it sounds like there is an entire observation (i.e., a `(1,100)` array) missing. For ANOVA involving multiple subjects this should have negligible effects because the magnitude of variability tends to be, in order of decreasing magnitude: between-condition, between-subject and within-subject. A single missing observation pertains to within-subject variability, but this is the least important variability for most ANOVA designs. More simply: adding additional observations will cause an individual's mean estimate to converge more closely to that individual's true mean, but improving within-subject mean estimates is usually inconsequential  between-subject and between-condition variance are much large.


<br>
<br>

> If I remove the data to keep the number of lines/data-points constant and the design balanced, Matlab turns these into zeros (as opposed to SPSS/excel etc., where it is clear there is a missing value). 

I don't quite understand this point. Do you mean that you have submitted a `(1,101)` array of zeros as a pseudo-observation? If yes, then this indeed could have big effects on the results, unless that subject's mean happens to be quite close to the null trajectory (i.e., all zeros).

As a rule of thumb: never add artificial data to impose balance. Instead remove real data to impose balance.

As an exercise (one that will generate un-reportable results) you can calculate the mean from the existing observations for that individual and submit this mean as the quasi-observation to impose balance.

**Comment by freddybrown1984** [comment]
Great stuff - thanks, Todd
