### ISSUE TITLE
FWHM From Mean and Standard Deviation

### ISSUE THREAD

**Issue by DCHartlen** [0todd0000/spm1dmatlab#178]
I have a conceptual question regarding how full width at half maximum is calculated. I understand that FWHM in SPM1D is proportional to the variance and residuals of all signals at each node. Then the mean FWHM across all nodes is used in subsequent calculations. 

There are a number of datasets in my field where results are published as a single mean signal with standard deviation provided at each point, instead of publishing every individual signal. This is particularly true of older but still valuable publications. It would be nice to be able to digitize this data and be able to use it with modern analysis techniques such as SPM1D. But the big hurdle I see is computing FWHM. 

Do you think it is possible to estimate the FWHM of a gaussian field from a single mean signal with the standard deviation provided at each point, instead of providing each individual signal? I understand that this request would mean a fairly large change in the architecture of SPM1D, and that isn't what I am requesting. I'm more interested if it is feasible or theoretically correct. FWHM for a gaussian distribution is proportional to standard deviation (usually 2*sqrt(2*ln(2)). Can this be extended to the concept of gaussian fields? I've toyed around with a couple of ideas to compute an FWHM value from a mean signal and standard deviation, but without much success getting the results to match the FWHM values produced by SPM1D. I think the big difference was coming from operations performed on the residuals in SPM1D.  I would love to hear your thoughts and expertise. 

Thank you!

**Comment by 0todd0000** [comment]
I expect that it is not possible to estimate the FWHM from just the mean and/or SD because (a) the mean and SD smoothness may not be directly related to the residual smoothness, and (b) the FWHM is a characteristic of the residuals. 

As an extreme example to illustrate the problem, imagine a constant SD across the 1D domain (i.e., perfectly smooth SD). The observations and mean could be completely uncorrelated (i.e., perfectly rough) even with this constant SD. Thus the SD by itself does not necessarily pertain to the actual data smoothness.

Part of the problem is that there are two types of Gaussian approximations to consider when characterizing Gaussian random fields:

(1) Single-point distribution:  this the distribution of data at a single domain point, and the SD characterizes this distribution.

(2) Convolution kernel:  convolving a certain kernel with uncorrelated data yields correlated (i.e., smooth) data. In the case of Gaussian random fields, a Gaussian kernel is convolved with perfectly uncorrelated (rough) data to yield smooth data. The FWHM parameter directly characterizes this Gaussian kernel, and indirectly characterizes both (a) the correlation amongst neighboring domain points, and (b) the residuals' gradient magnitude.

Note that The FWHM parameter pertains only to (2). From your description it sounds like you may be attempting to calculate the FWHM from (1). I don't this is possible, because the FWHM is not directly related to (1). All FWHM estimation procedures that I am aware of use only the gradient of the residuals, and not the mean or SD.

**Comment by DCHartlen** [comment]
Thank you Todd! I appreciate the time you took to explain this. You are right, I hadn't fully considered the convolution kernel you brought up. That helped cement why the operations on the residuals are necessary to compute FWHM. It is a bit of a shame there isn't another way; there is a lot of really good data out there that I think could benefit from reanalysis with a tool like SPM.
