### ISSUE TITLE
p-values reaching zero

### ISSUE THREAD

**Issue by Angelanieuwenhuys** [0todd0000/spm1dmatlab#18]
Hi Todd,

For one of my projects, I have been running one-way anova and post-hoc tests on a number of datasets. When performing inference, I am finding p-values that are simply ‘0’, as opposed to e.g. ‘8.5645e-9’. I am using version M.01.0003 (2014.06.27), but I have tried an analysis in the newest version that is online available, and I found the same results. 
It appears ‘impossible’ to me for a probability to reach ‘0’, or isn’t it? I am hoping you might provide me with some insight in this matter. 

Thank you,
Angela

**Comment by 0todd0000** [comment]
Hi Angela,

You're quite right that probabilities can never be exactly zero.  I suspect that the reason you're seeing "p = 0" is because the actual p value is so small that it's numerically difficult to compute.  In MATLAB the smallest floating point number is 2.2204e-16 (which you can see by typing "eps"), and at certain stages in the p value computation it is possible that the software is treating values smaller than that as zeros.

It's also possible that there's a bug in the software!

To check whether or not it might be a bug could you send one or both of the following: 

* A figure depicting the SPM for which "p=0.0" was generated.
* Details of the SPM and clusters. For example:


```python
>>  t = spm1d.stats.ttest2(yA, yB);
>>  ti = spm.inference(0.05, 'two_tailed',true, 'interp',true);
>>  disp( ti )
>>  disp( ti.clusters{1} )
```

which should yield something like:

```
SPM{t} inference
         z: [1x101 double]
        df: [1 18]
      fwhm: 20.5956
    resels: [1 4.8554]
     alpha: 0.0500
     zstar: 3.2947
     p_set: 0.0312
         p: 0.0312
```

and

```
  Cluster with properties:

    endpoints: [93.2746 100]
        csign: 1
    iswrapped: 0
       extent: 6.7254
      extentR: 0.3265
            h: 3.2947
           xy: [96.5343 4.5976]
            P: 0.0312
```




Cheers,

Todd

**Comment by Angelanieuwenhuys** [comment]
Hi Todd,

thanks for your help! Below you can find an example of a figure and the related information:

![t13](https://cloud.githubusercontent.com/assets/19794164/15856181/4a77ef4e-2cb4-11e6-8116-edeeee4b1828.png)


> t13 = spm1d_stats_ttest2(B, D);
> nTests     = 21;
> p_critical = spm1d_util_p_critical_bonf(alpha, nTests);
> options    = struct('two_tailed',1);
> t13i       = spm1d_inference(t13, p_critical, options);
> disp(t13i)


>  STAT: 'T'
>                 df: [1 823]
>             nNodes: 51
>                  z: [1x51 double]
>               beta: [2x51 double]
>                  R: [825x51 double]
>             sigma2: [1x51 double]
>               fwhm: 18.8785
>             resels: [1 2.6485]
>              alpha: 4.7847e-004
>         two_tailed: 1
>              zstar: 4.0495
>            extents: 37
>     extents_resels: 1.9599
>                  p: 0

I hope this is what you were looking for (it looks a bit different than yours...)
best,
Angela

**Comment by 0todd0000** [comment]
Hi Angela,

It looks like you're using an older version of the software.  Please download the most recent version:
www.spm1d.org/Downloads.html

Regardless of version, the result looks OK as "p = 0" because the probability is very small. To check you can use the probability calculator (in the newer version of the software):

```matlab
>>  p = spm1d.rft1d.t.p_cluster(k, u, df, nodes, FWHM)
```

where:

*   *k* = cluster extent  (i.e. temporal breadth with units: resels)
*  *u* = threshold (usually the critical test statistic value)
* *df* = degrees of freedom
* *nodes* = number of nodes in the trajectory (usually 100 or 101)
* *FWHM* = full width at half maximum (i.e. smoothness)

This "p_cluster" function computes the probability that random 1D Gaussian data with a smoothness of *FHWM* will produce a suprathreshold cluster as large or larger than *k* when thresholded at *u*. This probability gets very small as *k* increases.  For example, consider these results: 

```matlab
>>  spm1d.rft1d.t.p_cluster(1.0, 4, 9, 101, 20);   % p = 3.8255e-05
>>  spm1d.rft1d.t.p_cluster(1.5, 4, 9, 101, 20);   % p = 1.2305e-08
>>  spm1d.rft1d.t.p_cluster(2.0, 4, 9, 101, 20);   % p = 1.5865e-13
>>  spm1d.rft1d.t.p_cluster(2.5, 4, 9, 101, 20);   % p = 0
```

The probabilities get so small that their calculation becomes numerically difficult, so a value of zero is returned. The probabilities are small enough that a value of "0" shouldn't affect practical conclusions, nor should they cause difficulties for iterative probability calculations (e.g. in Bayesian inference).

If you have the Statistics Toolbox, you'll see that MATLAB's built-in calculations are similar.  For example, using the Statistics Toolbox's "tcdf" function (the cumulative distribution function for the t statistic) you can compute the probability that 0D Gaussian data will produce a t value which exceeds *u* as:

```
>> p = 1 - tcdf(u, df);
```

When *u* gets very high this probability becomes very small:

```matlab
>> p = 1 - tcdf(10, 9);     % p = 1.7891e-06
>> p = 1 - tcdf(100, 9);    % p = 2.5535e-15
>> p = 1 - tcdf(1000, 9);   % p = 0
```


When reporting these probabilities it might be best to use "p < 0.001" or "p < 1e-5" or something similar instead of "p = 0".


Todd

**Comment by Angelanieuwenhuys** [comment]
Hi Todd,

thank you for the extensive reply and clarifying the issue! I am reassured now that the results I am finding are the correct ones, and not due to a bug. Using the most recent version of the code, I indeed found the same result

```
p_critical = spm1d.util.p_critical_bonf(0.01, 21)
t13i = t13.inference(p_critical, 'two_tailed',true);
disp(t13i)
disp(t13i.clusters{1})
p=spm1d.rft1d.t.p_cluster(2.6825,4.0523,1,51,18.6394);
```
The returned p from the probability calculator (with different df) was alwas 0.

```
SPM{t} inference
         z: [1x51 double]
        df: [1 823]
      fwhm: 18.6394
    resels: [1 2.6825]
     alpha: 4.7847e-04
     zstar: 4.0523
     p_set: 7.7716e-15
         p: 0

  Cluster with properties:

    endpoints: [0 36.9088]
        csign: -1
    iswrapped: 0
       extent: 36.9088
      extentR: 1.9801
            h: -32.6806
           xy: [18.4976 -18.9070]
            P: 0
```

Thanks again!
Angela
