### ISSUE TITLE
SPM1D ttest2

### ISSUE THREAD

**Issue by drym1989** [0todd0000/spm1dmatlab#184]
Hi Todd,
I have acquired spectral data using Diffuse Reflectance Spectroscopy (DRS) in order to investigate the differences between normal and abnormal tissue. The X-axis represents the wavelength between 420 and 1000 nanometers (spectral range), while the Y-axis represents the normalized intensity. A DRS graph depicts how the intensity of reflected light from a sample varies across various wavelengths of light, from shorter wavelengths (such as ultraviolet) to longer wavelengths (such as infrared). I have attached a sample of literature-based spectra data. 
The null hypothesis is that spectral data obtained from normal and abnormal tissue at different wavelengths of light differ significantly. I intend to do SPM1D ttest2.
1) Can SPM1D analysis be performed on such data if the X-axis represents wavelength rather than time?
![normalVsAbnormal](https://github.com/0todd0000/spm1dmatlab/assets/145567780/63d5a155-7824-434b-b244-df675b0c1cfd)

**Comment by 0todd0000** [comment]
> Can SPM1D analysis be performed on such data if the X-axis represents wavelength rather than time?

Yes, the nature of the one-dimensional domain is irrelevant to the statistics. However, it is important to acknowledge that different domains can be presented in different manners. For wavelength and frequency scales occasionally logarithmic scales are used. For these data this does not appear to be a problem, but in general the domain should be constructed in a manner that is generally accepted for analysis.

In this particular dataset you may run into issues for wavelengths smaller than about 570 nm. Here it appears that many observations are zero or close to it. This generally means an skewed or otherwise odd distribution of data at these points, and therefore that the parametric assumption of normality may be inappropriate for this region. Nonparametric analysis may be more appropriate.
