### ISSUE TITLE
Sphericity

### ISSUE THREAD

**Issue by Kneerav** [0todd0000/spm1dmatlab#19]
************************************ MOVED TO PYTHON SECTION ***************************************

Hi Todd, 

First off, thanks for your terrific python package. I have read almost all of your papers related to SPM, and I had a couple of queries regarding the Python package that I was hoping you could answer. 
 
In short, I am comparing 3D kinematics and kinetics of participants across 5 different tasks. I am primarily interested in the knee joint injury implications, but am also looking at the hip and ankle joints. 

My plan is to conduct a repeated measures ANOVA (is there a vector field equivalent? Can Hotelling's be applied for multiple groups?) for each variable of interest for the 5 tasks, then conduct post-hoc paired t-tests with a Bonferroni correction for the comparisons. If this seems reasonable to you, I guess I would ask:

1. Given that the non-sphericity correction is approximate and has yet to be verified, what does this mean for publication outcomes? Would you recommend I use another method if sphericity is violated?
2. Is there a simple way to test for sphericity with these sorts of datasets? (Is there an SPM specific method for assumption testing e.g. sphericity or normality at each node?)
3. Finally, is it simply good practice to interpolate to ~100 data points? Some of my data is based on time, thus each participants data already has the same number of nodes. My concern is that the low number of time nodes (sometimes less than 20) might be influencing RFT related corrections. 

Hope that all makes sense. Again, any help you can provide would be much appreciated given your expertise in the area.

**Comment by 0todd0000** [comment]
Thank you very much for your questions.

Regarding Hotelling's test and multiple groups:  yes, such a test is available.  The multivariate equivalent of ANOVA is MANOVA, and **spm1d** currently offers one-way MANOVA procedures  ( *spm1d.stats.manova1*). Repeated-measures MANOVA and N-way MANOVA are also possible but are not yet implemented in **spm1d**.  *Post hoc* tests using ANOVA, Hotelling's tests and t tests are all certainly possible, but all are often overly simplistic. Future versions of **spm1d** will expand on multivariate functionality including more rigorous *post hoc* procedures.  

1. **Non-sphericity**.  From what I've seen in biomechanics datasets, non-sphericity generally has a much smaller effect on ultimate results than do other factors like:  (i) 0D vs. 1D inference procedures, (ii) multiple comparisons, and (iii) scalar vs. vector approaches.  Nevertheless, your point is well-taken because, when all of those factors are dealt with properly, non-sphericity can still have an effect on the results.  As you correctly note, the current version of **spm1d** does not yet contain a validated correction for non-sphericity. The implemented procedure (which comes from the SPM literature) is probably correct, but we've just not made the time to run the millions of simulations of random 1D data necessary to validate that procedure.  Fortunately there is an alternative and much simpler solution: non-parametric analysis.  Non-parametric solutions implicitly handle non-sphericity, and all non-parametric solutions are valid even in cases of large non-sphericity.  Moreover it's quite easy (albeit computationally intensive) to run non-parametric inference procedures.  Non-parametric inference will be available in the next major release of **spm1d**.  If you need a more immediate solution, it may be acceptable to compute standard deviation trajectories and then plot them for each group.  If there are large inter-group differences in standard deviations then it may be best to interpret results somewhat cautiously. It may also be worth noting that non-sphericity corrections will only ever raise the critical threshold.  Thus if your results fail to reach the threshold (under an assumption of sphericity) they will also fail to reach the threshold after accounting for non-sphericity.  Moreover, if your results soar well beyond the threshold it is almost certain that a non-sphericity correction will not affect those results. If when the results only just pass the threshold then those results should probably be interpreted cautiously.  

2. **Sphericity tests**.  Yes, and yes (and also a third yes: the following discussion applies equivalently to normality tests).  One could compute a non-sphericity test statistic at each node in the 1D trajectory then conduct a single test to compute the probability that spherical Gaussian 1D data would produce the same test statistic.  Another approach would be to estimate a single non-sphericity value for the entire dataset and test that value.  Unfortunately neither test is available in the current release of **spm1d**, but this is something we hope to add as non-sphericity functionality improves.

3.  **Interpolation to 100 data points**.  An excellent question!  This gets right to the heart of SPM.  A short answer is:  *the number of nodes is irrelevant provided the Nyquist criterion is exceeded*.  A slightly longer answer is: *reducing the number of nodes can disrupt the frequency content in your data, so the number of nodes should be selected in a way that retains the frequency content of interest*.  As a more practical example, consider a typical two-humped vertical ground reaction force (VGRF) trajectory during walking.  If we can safely ignore high-frequency signal following impact, then one could sample the VGRF data at 100 Hz, 1 kHz, 1 MHz or 1 GHz without affecting the overall trajectory because the vast majority of the frequency content lies well below 50 Hz. Similarly, you could resample VGRF data to 100, 1000, 1e6 or 1e9 data points and not affect SPM results.  The reason is that SPM calculates trajectory smoothness approximately as the average temporal derivative, and this estimate is quite stable to resampling provided frequency content does not change.  In other words, SPM considers the behavior of smooth, random 1D data that have the same number of nodes and the same smoothness as your data.  If your data is qualitatively unaffected by the number nodes, then SPM results will also be qualitatively unaffected.

Cheers,

Todd
