### ISSUE TITLE
two-factor anova difference in zstar value

### ISSUE THREAD

**Issue by CoraBora** [0todd0000/spm1dmatlab#194]
I would like to investigate the influence of insoles and speed on the joint movement of the knee, hip and ankle. 
To do this, I would like to run a two-factor anova for nonparametric data. If I run the anova using a loop (the data vector contains all joint data in x,y, and z-direction for all conditions) I get a different zstar-value (the red dashed line) than if I run the anova for each direction and each joint individually. I don't understand why this is and would be glad if someone could help me.

Loop (all joints)
for i = 1:3 %x,y,z-direction
    for j = 1:3 %Knee,Ankle,Hip
        FFn{i, j} = spm1d.stats.nonparam.anova2rm(data{i, j}', Einlage, Speed, SUBJ);
        FFni{i, j} = FFn{i, j}.inference(alpha, 'iterations', iterations);
    end
end

Individual Anova (only for the knee):
FFn_Knee_x        = spm1d.stats.nonparam.anova2rm(Knee_x', Einlage, Speed, SUBJ);
FFni_Knee_x       = FFn_Knee_x.inference(alpha, 'iterations', iterations);

**Comment by 0todd0000** [comment]
If you are using less than all iterations then this is expected because **spm1d**'s nonparametric procedure uses random permutations. If you would like to reproduce results exactly then you need to control the random number generator's state, for example using:

```octave
s = spm1d.stats.nonparam.anova2rm(Knee_x', Einlage, Speed, SUBJ);

rng(0)     % set the random number generator seed
si_1 = s.inference(alpha, 'iterations', iterations);
si_2 = s.inference(alpha, 'iterations', iterations);  % si_1 and si_2 are different

rng(0)     % set the random number generator seed
si_3 = s.inference(alpha, 'iterations', iterations);  % si_1 and si_3 are equal
```

While the `si_1` and `si_2` results in the code snipped above will not be exactly the same, they are not expected to yield qualitatively different results provided `iterations` is suitably high (usually `iterations = 1000` or `iterations = 10000` is suitably high). Nonparametric permutation procedures generally become increasingly stable as `iterations` increases.

An excellent description of permutation tests is provided in [Nichols and Holmes (2002)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6871862/), especially in the section titled "Permutation Tests".  **spm1d** uses the permutation procedures described in this article.

**Comment by CoraBora** [comment]
Thank you very much for your quick reply!
Just so that I am not misunderstood, the curves (in this case si_1 and si_2), did not actually differ in my case. Only the red dashed line was not at the same height.

**Comment by 0todd0000** [comment]
The red dashed line is the critical threshold, which is the key calculation made during statistical inference. Permutation is used only for inference and not for test statistic calculation. This means that the test statistic (i.e., t-value) will not change, only inference results (i.e., p-values and critical thresholds) will change. If there is only a small change in the critical value it is not a problem. If there is a big change then it is indeed a problem, and would suggest that `iterations` is too small.  In general `iterations` should be at least 1000 but 10,000 is usually preferable for numerically stable results.

**Comment by 0todd0000** [comment]
Here are several relevant post hoc issues:
https://github.com/0todd0000/spm1d/issues?q=post+hoc
https://github.com/0todd0000/spm1dmatlab/issues?q=post+hoc
If these posts do not answer your questions please post your questions in the most relevant issue page(s), thanks!
