### ISSUE TITLE
Fill the gap between curve and line

### ISSUE THREAD

**Issue by CoraBora** [0todd0000/spm1dmatlab#196]
I am trying to generate a similar plot with my own features. How can I color the significant areas? I only manage to color the entire area between the curve and the threshold. I have tried many different options but unfortunately I can't find the solution. I have already asked in the general Matlab forum but I didn't get any further there either.

This is my code:

curve = F(:,2)';
line = 13;
plot(curve,'k');
hold on;
area(x,curve,line,'FaceColor','c','LineWidth',1);
yline(line, '--r',LineWidth=2)

![untitled](https://github.com/0todd0000/spm1dmatlab/assets/153523754/ba7394b8-a543-40b4-a4bf-47be8bff9c8e)

This is how it should look (only the shaded areas):
![image](https://github.com/0todd0000/spm1dmatlab/assets/153523754/bb63ec64-0f93-4d64-9926-fc1ccd56f24b)

**Comment by m-a-robinson** [comment]
I am not sure that Matlab has a build in function for this (unlike Python -> Matplotlib). A quick search found this on the Matlab file exchange https://uk.mathworks.com/matlabcentral/fileexchange/47151-fill_between which would seem to do what you want. 
You can of course customise the existing plot should you wish rather than having to create a new plot from scratch.
Regards
Mark
