### ISSUE TITLE
Comparison between discrete and continuous data

### ISSUE THREAD

**Issue by SimonBarruebelou** [0todd0000/spm1dmatlab#199]
Dear Prof Pataky,

We are currently working on comparing 2 different way of data analysis with the same set of clinical data. We would like to promote angle-specific analysis (for torque-angle curves) and show that they provide greater asymmetry indexes than peak torque analysis (comparison between the maximal value of each torque-angle curve, independently from the angle).

To this end, we would like to use 2 different approaches : 
- Discrete approach : here we summarize the continuous vector to a single value (for example, the median value) and we compare it with the value already calculated (paired t-test)
- Continuous approach : here we would like to use SPM and compare our vector to the discrete value that we reported at each point (paired t-tests at each measuring point), cf figure. 

Do you confirm that, even if the tool has not been created to compare discrete and continuous data, and if the line does not correspond to physiological data, what we are doing is mathematically correct and make sense for you ?

Thank you very much in advance for your response.

Sincerely

Simon Barrué-Belou

![fig_finaletest](https://github.com/0todd0000/spm1dmatlab/assets/116175467/9f5ae853-5f00-4749-b215-089fb3ee4b10)

**Comment by 0todd0000** [comment]
This approach sounds fine, in general, and the nature of the 1D domain is irrelevant. Usually the 1D domain represents time, but it can alternatively represent space or any other variable. Provide 1D means and standard deviations can be meaningfully calculated the domain can be anything.

In this case I'd suggest trying a one-sample t-test. Paired and two-sample tests presume that there are `N` complete 1D measurements for both groups / conditions, where `N` is the sample size. Since that is not the case here, I believe that it may be more appropriate to regard the discrete value as the datum `mu` for a one-sample test. From the figures above it looks approximately like `mu=0.2`, so the code would look something like this:

```octave
mu  = 0.2;   % hypothesized mean
spm = spm1d.stats.ttest(y, mu).inference(0.05, 'two_tailed', true);
```

Note that I've set `two_tailed` to `true` because there are relatively large negative t-values in the left two panels. If you do not have a strict hypothesis regarding effect directionality then `two_tailed` should be set to `true`.

**Comment by SimonBarruebelou** [comment]
Thank you very much for your feedback, it is very helpful !
Happy to hear that the approach seems correct. 

The 4 different conditions represented here correspond to 2 x 2 independent variables in which we compare 2 methods of data analysis. I understand that I can use one-sample t-test setting two-tailed to compare the methods in the 4 conditions separately.
If I would like to integrate the conditions in the statistical model, for the discrete approach, if I'm not wrong, I will have to use a two-way MANOVA, with the 2 methods of data analysis as dependent variables and the factors as independent variables (contraction mode and speed).
If I want to use the same model with continuous data, I can't find the two-way MANOVA in the spm1d I have. Maybe this functionality has not been developed yet.
Do you have any solution for that ? Or should I use one-way MANOVA and separate the two independent variables ?

Thanks again very much for your help.

Sincerely 

Simon

**Comment by 0todd0000** [comment]
There are several details here so I shall only answer your direct questions.

> Do you have any solution for that ? Or should I use one-way MANOVA and separate the two independent variables ?

- Currently only one-way MANOVA is supported in **spm1d**

- MANOVA and other multivariate procedures are meant for multiple *dependent* variables. The *dependent* variable in this case is I believe torque (or moment).
