### ISSUE TITLE
Different number of measurements for within-subject effects

### ISSUE THREAD

**Issue by AlexPleger** [0todd0000/spm1dmatlab#202]
Hi,

we collected reaching data under three conditions in an n-back task (1back, 2back, 3back). Subjects were tasked with observing a sequence and pointing towards one of five targets displayed on a screen.
Due to instances of pointing towards the wrong target and violating reaction time constraints, we excluded some trials per subject.

I'm wondering what possible ways there are to run SPM or SnPM on the dataset. So far, my ideas are
1) averaging the trajectories per subject and condition and use these in a one-way repeated measures ANOVA (potentially loosing information due to the averaging)
2) based on [#12](https://github.com/0todd0000/spm1d/issues/12) using something like [Random Effects](https://spm1d.org/doc/RandomEffects.html) with dummy codes for the condition variables.

Also, I am wondering whether the non-parametric version (spm1d.stats.nonparam.anova1rm) might be appropriate and able to handle this case, considering it is based on resampling from the data?

Best,
Alex

**Comment by 0todd0000** [comment]
I agree with your first suggestion:  first calculate within-subject and within-task means, then submit only these means to ANOVA. While this may indeed lose a bit of information, the final results will likely be unaffected by this approach. One way to check is to produce results for the following situations:

- (1) Using only means
- (2) Using one randomly selected observation for each individual and each task
- (3) Repeat (2) several times

The results will change numerically (i.e. F-values, critical thresholds and p-values), but these numerical changes will likely be small. If the changes have no qualitative effect on the interpretations then this would be encouraging to know that the simplification of (1) is an adequate one.

<br>
<br>
<br>

Regarding the two other points:

- Your Random Effects suggestion may also be possible, but is not directly supported in **spm1d** so it is difficult to support in this forum. My suspicion is that this would be an unnecessary complication. In fact it may be exactly the same as (1), depending on the model. Calculating within-subject means is indeed a Random Effects approach, where parameters (in this case: means) are calculated in a first-level analysis before being submitted to a second-level analysis.
- Nonparametric resampling could also work, but I am concerned that it might not be appropriate to use **spm1d**'s procedures because they use a test statistic that assumes balance. This might be an inconsequential approach, but I am not certain of this point, as there may be odd dataset characteristics that could bias resampling results.
