### ISSUE TITLE
ANOVA multiple trials

### ISSUE THREAD

**Issue by FluxEline** [0todd0000/spm1dmatlab#22]
Hi all,

During an SPM workshop, you advised against averaging trials, but instead inserting all available trials in the SPM.  However, I found some difficulties with implementing this in the tests. For example, I want to perform a repeated measures ANOVA. For each subject, I collected multiple trials. 
When you perform an anova1_bs test, you insert the data and the factor. For the within subject analysis you add the subject information. In this case the subject information is not present for the between-subject analysis. Hence you act as if you have more subjects than you actually have, thereby you decrease the between-subject effect. 
Therefore I was wondering if you can add subject information to the 1 factor within-subjects ANOVA, or if I should use the average per subject.

Thank you very much!!

Eline

**Comment by 0todd0000** [comment]
Hi Eline,

For between-subjects analysis you are quite correct.  If SUBJECT is not explicitly modeled in the ANOVA, then adding more observations is like artificially adding more subjects.

For within-subjects (WS) analysis SUBJECT must be modeled, and the results should not be affected by adding multiple observations because the degrees of freedom (DF) do not increase;  the DF are  determined by the number of subjects and not the number of observations per subject. The only difference you should see by adding observations is in the smoothness estimate, which might slightly affect results like the critical threshold, but likely not qualitatively so.  The smoothness estimate, like mean and standard deviation estimates, becomes more accurate when more observations are available. Thus for WS designs it is generally best to include all available observations.

Todd

**Comment by FluxEline** [comment]
Hi Todd,

Thank you for your clear response. 

You say that for WS analaysis, SUBJECT must be added, but is it also possible to add this parameter to the BS analysis? Since it would be nicer to use the same data set for all analysis, instead of averaging the dataset halfway through. The same goes for the post-hoc test. Currently I can perform a WS ANOVA with all observations included. However, for the post-hoc (paired-t) testing, I cannot add the variable SUBJECT. Hence including all observations is again like artificially adding more subjects. Therefore I average over all observations before performing the post-hoc t-test. I was wondering if this is the only correct way?

Best, 
Eline

**Comment by 0todd0000** [comment]
Hi Eline,

The problem you describe is indeed a valid one and unfortunately a limitation of the non-automated *post hoc* procedures in the current version of **spm1d**.  In future versions the *post hoc* procedures will be clearer and more automated to make coding easier.

For now, the paired testing procedure you describe is indeed the best way.  The discrepancy in the coding interface (between **spm1d.stats.anova1rm** and **spm1d.stats.ttest_paired**) exists because WS ANOVA is not "paired" in exactly the same way that a paired t test is "paired".  A paired t test considers each of the *N* pairs of observations to be independent, but WS ANOVA instead assumes that each of the *N* subjects are independent.  That's why it's possible to add multiple observations per subject to a WS ANOVA.  In other words, a simple paired t test is the correct *post hoc* procedure for WS ANOVA if and only if there is one observation per subject.

Todd
