### ISSUE TITLE
Reporting of fragmented clusters

### ISSUE THREAD

**Issue by incensesmoke** [0todd0000/spm1dmatlab#23]
Dear all,

In SPM, is there a way of reporting a fragmented cluster?

More in detail: In the attached files (post hoc comparision, two tailed ttest, corrected p-value) there are three significant suprathreshold clusters, however they are seperated by rather short intervals that on first sight seem to be functionally irrelevant. Therefore my first question, is there any way of surpressing these intervals to make a single cluster out of the data? Is there a typical justification for  this?

And in this light my second question: What are the significance values that you would report in either case? We have set alpha at 0.05, corrected for number of tests it is then 0.0102. P-set from the inference object is 1.21e-11 and the individual clusters are [0; 2.2e-05; 5.2e-05]. Does it make sense to report the individual cluster p-values? Do we need to backwards correct these values for number of clusters/number of tests if we report them?

Thanks very much in advance for your time!

Chris

[SPM_for_example.zip](https://github.com/0todd0000/spm1dmatlab/files/371443/SPM_for_example.zip)

**Comment by 0todd0000** [comment]
Hi Chris,

I am unaware of any theory regarding cluster de-fragmentation.  The only partially relevant theory of which I am aware is a minimum cluster size thershold (e.g. ignore all clusters less than two nodes).  This setting can be useful when the frequencies are high, because multiple small clusters are likely, possibly caused by noise.  In the neuroimaging literature a minimum cluster size threshold is occasionally used, but I'm unaware of any published justification for using a cluster-size threshold on biomechanical datasets.  Moreover, this threshold would increase rather than decrease fragmentation so would not be particularly useful in your case.

Perhaps the best approach is to recognize that these statistical results are just approximations to potentially real effects and are not real effects themselves.  If you increased statistical power (e.g. using a larger sample) then the you would expect fewer fragmented clusters.  In order to report fragmented clusters I think it would be sufficient to report "null hypothesis rejection at alpha=0.05" and then supplement that statement with a qualitative description of the results.

Regarding your last question:
If you have used a Bonferroni correction, then you can backwards-correct using: **spm1d.util.p_corrected_bonf**. For example, if you compute a corrected threshold based on _N_=5 tests as follows:

```
>>  alpha = 0.05;
>>  N = 5;
>>  p_critical = spm1d.util.p_critical_bonf(alpha, N);  
```

Then you can compute corrected p values as follows:

```
>>  p = 0.0102;
>>  N = 5;
>>  p_corrected = spm1d.util.p_corrected_bonf(p, N);
```

Please find an example of this type of correction near the bottom of this page:
http://www.spm1d.org/doc/PostHoc/anova.html?highlight=p_corrected_bonf


Cheers,

Todd

**Comment by incensesmoke** [comment]
Hi Todd,
Thanks very much for the rapid response! It's a pity that there is no "standard" argumentation when there are very small gaps between supra-threshold clusters. From your explaination I also guess it's not really feasable to set a minimum break size to seperate two clusters? Also, from what I've understood there is a correction of p_set depending on the number of clusters which would then be affected?

We will interpret the results as p<0.05 and provide a qualitative description as you have proposed...

Thanks for your time and input!

**Comment by 0todd0000** [comment]
Hi Chris,

There is no parametric solution for a minimum break size of which I am aware.  The only theoretical probabilities from Random Field Theory pertain to (i) cluster extent and (ii) cluster integral, and the former is much simpler and used much more often than the latter.  I don't think it would be easy to derive a parametric solution for minimum break size because the test statistic can conceivably dip down to zero between adjacent clusters (or even become negative for the T statistic);  in that case I expect any theoretical solution would yield undefined probabilities.  It may be possible to generate a minimum break size criterion non-parametrically based on a particular dataset, but I haven't seen that done before in the literature, and it sounds like a technically challenging prospect.

Regarding p_set:
This probability is indeed affected by the number of clusters, and it is always is smaller than or equal to the minimum cluster p value.  There is no correction applied;  p_set simply becomes smaller as the number of clusters increase.

Cheers,
Todd
