### ISSUE TITLE
Related to my previous post (error performing t-test

### ISSUE THREAD

**Issue by PouyanMehryar** [0todd0000/spm1dmatlab#25]
Dear Tod,

I wonder if you could help me on the issue that I have mentioned in my previous thread. 
It was established that SPM cant not be used for my data because I only have one trial.
How would you go about to statistically analyse such data when you only have limited number of trials (In my case only 1 from different conditions)? most of the data that I have do not hold normality assumptions as the shapiro wilk normality test is significant (P<0.05). In this case do I need to use a non-parametric test  (Wilcoxon sign rank)??

Could I still use the parametric pair-t test in one of the statistical packages like SPSS even though the data is not normal? and I still dont understand why the data is not normal while there are 60 points in each trial which satisfy the rule of thumb of having more than 50 observation.

Thank you in advance for your response.

**Comment by 0todd0000** [comment]
Statistical analysis requires more than one trial because effects only have statistical meaning when they are compared to the underlying variability. This is true of all statistical analyses, including parametric procedures, non-parametric procedures, hypothesis testing and machine learning.

Imagine that you have two (1 x 1) observations, one from each of two groups:
```
yA  = [5]
yB = [10]
```
You can compute the difference (yA - yB), but you can't conduct statistical analysis because there is no variability.

Now imagine that you have two (1 x 60) continuum observations, one from each of two groups:
```
yA  = [5 6 7...  2 1 2]
yB = [10 15 11...  16 15 14]
```
Like above you can compute the difference continuum, but you can't conduct statistical analysis because there is no variability.  A single (1 x Q) continuum observation contains Q values, and Q may be larger than one, but but those values are just used to approximate the single continuum.  There are not Q independent observations.  

Perhaps another way of thinking about it is through sampling frequency:
Imagine that you measure a single vertical ground reaction (VGRF) trajectory during walking or some other activity.  You could measure that VGRF continuum at 1 Hz, 10 Hz, 100 Hz, 1000 Hz, 1 MHz, 1 G Hz, etc., but you are not adding observations when you increase sampling frequency.  You are simply using more discrete data points to approximate a single continuum.

Todd

**Comment by PouyanMehryar** [comment]
Dear Todd, 

Thank you for your comprehensive explanation.

**Comment by 0todd0000** [comment]
You're very welcome.  Please feel free to create new issues if any other problems arise. 
Todd
