### ISSUE TITLE
3-way ANOVA with EMG data

### ISSUE THREAD

**Issue by romainmartinez** [0todd0000/spm1dmatlab#26]
Dear Todd,

I read with great interest your publications regarding SPM. I used the SPM1D package on my data, but I have some doubts about my methodology (test selection, post-hoc). Being in Canada, I cannot attend your Workshops, and that’s why I  am contacting you by email.

My current study focuses on the effect of gender on shoulder muscles activation during a handling task. 29 men and 29 women did participate in the study where the experimental task was to move a box of different masses (6, 12 and 18 kg) on ​​shelves located at the hips, shoulders and eyes levels.

My independent variables are:
• Gender: male or female
• Box weight: 6, 12 and 18 kg
• Heights: hips—shoulder (H1); shoulder hips (H2); hips—eyes (H3); eyes—shoulders (H4); shoulders—eyes (H5); eyes—shoulders (H6).

My dependent variable is the EMG envelope of 13 muscles.

My procedure is as follows:

• After processing my EMG data, I conducted an ANOVA of three factors: gender, height, weight (spm1d.stats.anova3) and I got an interaction effect between my factors.
• I then conducted a post-hoc procedure consisting of making t-tests (spm1d.stats.ttest2) between men and women signals for each condition (18 t-tests performed), with a Bonferonni corrected _p_ (2 sexes * 3 * 6 mass height = 36, so p = 0.05/36 = 0.0014).

post-hoc tests conducted:
6kg at H1, H2, H3, H4, H5 and H6
12kg at H1, H2, H3, H4, H5 and H6
18kg at H1, H2, H3, H4, H5 and H6

Could you confirm my ANOVA 3-way choice for this study and my post-hoc procedure (knowing that post hoc is currently in development in your team) ?

Thank you in advance for your time,
Best regards,

—Romain

**Comment by 0todd0000** [comment]
Hi Romain,

Thank you very much for your interest in **spm1d**!

Your approach sounds fine in general, except that your dependent variable is multivariate (i.e. 13 muscles) so the best approach is probably three-way MANOVA.  Unfortunately only one-way MANOVA is available in the current version of **spm1d**.

As an alternative, the Bonferroni approach you describe is fine, but since Bonferroni corrections are almost always more conservative than MANOVA corrections, there are two implications:

1.  If your results reach significance after a Bonferroni correction they would certainly reach significance in MANOVA.  Thus there is no problem interpreting Bonferroni-corrected significance as "significant".

2.  If your results fail to reach significance, but come close to breaching the critical threshold, it is quite possible that MANOVA would find them significant. It's therefore best to interpret non-significant results cautiously when using Bonferroni corrections.

The only other suggestion I'd have is that you may also want to correct for the 13 separate **anova3** tests on each of the muscles, then correct on top of that correction for post hoc tests.  That is:

1.  Bonferroni corrections across the 13 **anova3** tests:  p_critical = 0.003938.

2. Subsequent Bonferroni corrections across the (13 x 18) = 234 t tests:  p_critical = 0.000219.

However, this depends partly on the purpose of the experiment.  If you wish to identify real effects, then protecting against Type I error is most important, so the conservative Bonferroni approach is probably fine.  If, however, your goal is to show that there is no effect of the independent variable(s) on the dependent variable(s), then protecting against Type II error is most important, so it may be best to use an uncorrected threshold of alpha.

Todd

**Comment by romainmartinez** [comment]
Hi Todd,
Thank you very much for your answer.
I'll try the different options with my data awaiting the new features that will be available on spm1d.

**Comment by 0todd0000** [comment]
You're very welcome.  Note that the next major release of **spm1d** (version 0.4) will be ready in October, but will unfortunately not offer two- or three-way MANOVA.  Those features might be available in v.0.5, but we're not yet sure.  Please see the link below for a list of features we plan to implement in future releases:
[Link to **spm1d** feature requests on github.com](https://github.com/0todd0000/spm1d/issues/45)
Todd

**Comment by 0todd0000** [comment]
Please note that **spm1d 0.4** was released today (01 October 2016).  I'll close this issue for now, but if you have any follow-ups please feel free to post them here. Otherwise please feel free to create a new issue.
Todd

**Comment by romainmartinez** [comment]
Hi Todd,

I re-open this thread because I have some issues with choosing the right SPM test. I’m currently doing another analysis, which is similar to the one I described to you, with:
- **4 dependent variables**: contributions of 4 different joints
- **3 factors**: sex (2 levels) – weight (2 levels) – height (6 levels)

Previously, I followed your advice and my statistical plan was the following:

1.	I did four 3-way ANOVA for each dependent variable, with a p corrected:
`p_corrected = 0.05/4`
2.	I did my post-hoc procedure (*with t-test*) between each condition, with a p corrected:
`p_corrected = 0.05/(4*12)`

However, I have some troubles in reporting the results. Indeed, I think I don’t choose the right statistical test because **I just want to describe the effect of gender on the dependent variables, depending on the weight and height**. Thus, the posthoc tests that I want to include in my results compare only the two sexes within the different conditions. To illustrate my point, you’ll find a figure with the significant area of the 48 post-hoc tests. 

My question is the following: which approach do you think is correct to describe the effect of gender on several dependent variables:
1.	Using the approach previously describes (*3-way ANOVA*), and only report post-hoc tests between sexes within the different conditions.
2.	Using a one-way MANOVA, and only report post-hoc tests between sexes within the different conditions.

Again, thank you very much for your availability and your fantastic package.

*- Romain Martinez.*

**Comment by 0todd0000** [comment]
Hi Romain,

From your description it sounds like repeated-measures (RM) ANCOVA (or RM-MANCOVA for four dependent variables) is the correct model.  Only non-RM ANCOVA is implemented in the current version of **spm1d**  (see  **spm1d.stats.glm**).  Since the actual model your looking for is not available, I'd recommend doing a variety of analyses like those you suggest, provided you acknowledge the limitation that your analyses are non-ideal *post hoc* explorations of the real model.

Todd
