### ISSUE TITLE
Understanding the dataset

### ISSUE THREAD

**Issue by millysfabrielle** [0todd0000/spm1dmatlab#4]
Hello Tood,

I am opening this issue, because I would like to understand how to organize the data set to use the scripts in python.

First of all I'm trying to recreate the same simulation as provided by Appendix A in you article "Vector field statistics for objective center-of-pressure trajectory analysis during gait, with evidence of scalar sensitivity to small coordinate system rotations" (http://www.sciencedirect.com/science/article/pii/S0966636214000630)

![untitled](https://cloud.githubusercontent.com/assets/4121237/8640165/4dea7f96-28c5-11e5-843b-b9b5615e46a3.png)

In this way, customize the example "ex_hotellings_paired_Pataky2014" to load the simulation values instead the original data set, as follow:

![untitled2](https://cloud.githubusercontent.com/assets/4121237/8641947/54cdb674-28f3-11e5-8dbc-517a0f1debff.png)

I read the documentation of the Multivariate tests, but I did not understood how to construct that matrix as described:

**In all multivariate 1D tests dependent variables are (J x Q x I) arrays
J = number of 1D responses
Q = number of nodes to which the 1D responses have been resampled
I = number of vector components**

Thank you for your attention.

**Comment by 0todd0000** [comment]
Hi Milly,
The Appendix A example contains 0D data, not 1D data, so the 1D example is not directly relevant.
Instead, please follow the 0D example here:
**./spm1d/examples/stats0d/ex_hotellings2.py**
For 0D analysis the data should be stored in **(J x I)** arrays.
Todd

**Comment by millysfabrielle** [comment]
Hello Tood, sorry for taking your time, but I would like to ask few more questions.

I will try to explain my experiment to show my doubts.

I am using SPM1D to analyze the elbow joint trajectory between two different motion capture systems (Kinect x Vicon). Five subjects participated in the experiment. The trajectory have 1692 samples. Thus, each (1692 × 3) elbow trajectory was regarded as a single vector field r(q) = {rx(q) ry(q) rz(q)}.

In this case, to perform Hotelling's paired T2 test  I used the **matlab version** of the 1D example **./spm1d/examples/stats1d/ex_hotellings_paired_Pataky2014.m**. After that I performed post hoc t according to the example **./spm1d/examples/stats1d/ex1d_ttest_paired.m**. 

I would like to ask, If I have not committed any mistake, what means the high SPM {T2} threshold since statistical difference was found in post hoc on rz(q)

The following images show my results:

**Hotelling's paired T2 test on r(q)**
![smp-t2](https://cloud.githubusercontent.com/assets/4121237/8663789/b5703dc8-29a5-11e5-96d7-65a55bf78104.png)


**Post hoc scalar field tests on rx(q), ry(q) and rz(q), respectively**
![smp-t x](https://cloud.githubusercontent.com/assets/4121237/8663792/b8364494-29a5-11e5-8831-a695a1aaf08d.png)
![smp-t y](https://cloud.githubusercontent.com/assets/4121237/8663793/b9992f04-29a5-11e5-942c-f82db21d9fab.png)
![smp-t z](https://cloud.githubusercontent.com/assets/4121237/8663794/ba9d0e7a-29a5-11e5-9275-52d872dbe282.png)

Thank you for your attention

**Comment by 0todd0000** [comment]
Hi Milly,
Thank you for your question.  There are a number of issues to consider:

1. Post hoc analysis, general justification.  Strictly speaking, post hoc analyses are not justified unless the main test reaches significance.   This is true for both ANOVA and multivariate analyses.

2. Post hoc analysis, correction for multiple comparisons.  You must adopt a correction for multiple comparisons when performing post hoc tests. For univariate data (i.e. ANOVA), the simplest way to correct for multiple comparisons is to use a Bonferroni correction (see **spm1d.util.p_critical_bonf**).

3. Multivariate vs. univariate results.  Multivariate results and univariate results are not directly comparable because univariate analyses do not consider the covariance amongst the variables.  As you can see in Table S1 (at the top of this Issue), the multivariate results can be very different from the univariate results.  Post hoc results for the X, Y and Z components, for example, are generally not valid because they assume that these components are independent, which is only very rarely true.  Appropriate post hoc tests for multivariate analyses use the covariance matrix to retain alpha across the post hoc tests.  These procedures are not yet available in **spm1d**.

4.  Multivariate analyses, small sample sizes.  The sample size should generally be 3-to-5 times greater than the number of vector components.  In this case there are three vector components, so a sample size of five is probably too small to make meaningful conclusions.  The main reason is that there are six variance / covariance components (X, Y, Z, XY, XZ, YZ), and you need larger sample sizes to estimate those accurately.  When the sample size is small, the critical threshold can rise to extremely high levels, as you observed in your Hotelling's paired test.

5.  Smoothness.  The data appear quite rough.  When the data are rough the thresholds will be quite high.

6.  Cyclical movements?  It appears that the signal is cyclical, with about five cycles (in the rz data)?  If that's true it might be better to treat each cycle as a separate observation.  This might explain why there are very large T<sup>2</sup> maxima at about times=420, 800, 1150.

Todd

**Comment by millysfabrielle** [comment]
I really appreciate your help, with these new information I will discuss with my guiding professor about the size of our samples and also about analyze each cycle separately.

Thank you once again.

**Comment by 0todd0000** [comment]
No problem, if any other problems arise please feel free to open a new issue.
Todd
