### ISSUE TITLE
Assumptions on data

### ISSUE THREAD

**Issue by KrisJonesUlster** [0todd0000/spm1dmatlab#41]
I was hoping you would have time to answer a quick question on SPM methods (or point me in the right direction in the literature). 
 
I was watching a Youtube video of a lecture given by Jos Vanrenterghem (https://www.youtube.com/watch?v=utWErRzrcO4) which I think did a good job of explaining the concepts. During this video it is noted that biomechanical data displays ‘spatiotemporal smoothness’ – which makes it suitable for analysis using SPM. The concept of smoothness conveyed in video was that data points are related to each other and not random or independent, however, the mathematical definition of a smooth function is one which is continuous in all derivatives. Of course there might be a number of situations where experimental data do not fit this criteria.
 
My question is: What assumptions are made of the input data for SPM? Is the trajectories displaying smoothness one of them?

**Comment by 0todd0000** [comment]
I agree with the definition that a smooth function is one which has continuous derivatives.  That definition can be resolved in the context of experimental data by regarding an experimental 1D measurement as a discrete approximation to a continuous 1D process.

From that perspective SPM makes no assumptions regarding smoothness or continuity, it instead assesses both from the data you submit for analysis.  It can handle data with any smoothness (from infinitely smooth straight lines to perfectly rough, uncorrelated data) and can also handle any geometry (continuous or piecewise continuous from time = 0% to 100%).


- **Note 1**:   other assumptions.  SPM makes a number of other assumptions (e.g. random sampling, independent measurement errors), but those assumptions are not unique to SPM. The reply above pertains only to assumptions regarding data smoothness and continuity.
- **Note 2**:  sampling frequency.  Related to Note 1, the 1D measurement must follow information theory's requirements regarding sampling frequency, and in particular must have suitably high frequency to capture the frequencies of interest.  If the sampling frequency is too low one risks signal aliasing, implying that the data should not be analyzed, using SPM or any other method.
- **Note 3**:  piecewise continuous data.  This type of data occurs occasionally in Biomechanics. For example:  the flight phase in vertical jump introduces an apparent discontinuity, where ground reaction force drops to a constant zero, then rises again upon impact.  Even in piecewise datasets such as this the data still meet the mathematical definition for continuity because the derivative is continuous at each point in time, and is zero during the flight phase.  I've yet to see a 1D dataset in Biomechanics that is truly piecewise continuous in the mathematical sense, where the derivative is not continuous across the whole 1D measurement domain.
- **Note 4**:  extremely rough data.  The rougher the data become, the more severe the random field theory (RFT) threshold must become in order to retain a Type I error rate of alpha across the entire 1D domain.  At some point (approximately FWHM=2.5, or extremely rough data) the RFT threshold becomes equivalent to a Bonferroni threshold.  By default **spm1d** uses the Bonferroni threshold if it is less severe than the RFT threshold;  this default setting retains alpha more accurately than using only a pure RFT threshold. That default setting can be overridden using the "withBonf" keyword argument when calling "inference", as in the code snippet below. Unless the data are very rough the "withBonf" keyword will have no effect.
```
>>  spm       = spm1d.stats.ttest(Y - mu);
>>  spmi      = spm.inference(0.05, 'withBonf',false);  %default:  withBonf=true
```
- **Note 5**:  anisotropic smoothness.  It is conceivable that smoothness is not constant across the entire 1D domain.  For example, impact forces at heel strike in walking usually have higher frequencies than do forces during the remainder of the gait cycle.  **spm1d** uses only the average smoothness, which is practically identical, within numerical tolerances, to an explicit correction for anisotropy.  Thus one needn't be too concerned with anisotropy.  This issue is described in detail in:    Worsley, K. J., et al. (1999) "Detecting changes in nonisotropic images." *Human Brain Mapping* **8**(2-3): 98-101.



Todd

**Comment by 0todd0000** [comment]
Hi, I'm closing this issue for now, but please feel free to re-open it and/or post a new issue if anything is unclear.
Todd
