### ISSUE TITLE
Group (n=3) x time (n=3) analysis in SPM

### ISSUE THREAD

**Issue by gillianweir** [0todd0000/spm1dmatlab#43]
Hi Todd,

I am running some analysis on 1D data over the stance phase of walking. I want to compare left and right limbs for a treatment group against each other and also to a control group at three time points as per the attached figure. 
![design](https://cloud.githubusercontent.com/assets/25989055/23384134/863a6eec-fd17-11e6-8f9f-ce96e00f5216.png)

I have run spm1d.stats.anova2onerm three times, comparing; 1) treatment left vs treatment right limbs; 2) treatment left limb vs control group limb, and; 3) treatment right limb vs control limb. Then I have run  spm1d.stats.anova1_posthoc to follow up significant main effects for time and spm1d.stats.ttest_paired to follow up for interaction effects for group and time. 

Is this the most appropriate design?

Many thanks again,

Gill

**Comment by 0todd0000** [comment]
Hi Gill,

This is a tricky one partly because it's unclear whether left- and right limbs are directly comparable, but if we slightly modify "left" and "right" to be "injured" and "uninjured" then the design becomes easier to discuss. Also, this reply assumes that the same subjects perform at each of the three Times.

**CASE 1**:  Total number of Treatment subjects = 20

If the ten subjects in "Treatment group limb 1" are different from the ten subjects in "Treatment group limb 2", then all data can be analyzed using a single two-way ANOVA with one repeated-measure (RM) (**spm1d.stats.anova2onerm**).

**CASE 2**:  Total number of Treatment subjects = 10

If the ten subjects in "Treatment group limb 1" are the same as the ten subjects in "Treatment group limb 2", then things become slightly more complicated. In particular, I don't think it's possible to analyze the entire dataset using a single design because there is nothing in the Control group which can be compared to the Treatment group's Injured - Uninjured difference.  So in this case I think it's correct to conduct three separate analyses as you suggest.  I'd run those three analyses as follows:

1) *Treatment Injured vs Treatment Uninjured*:  **spm1d.stats.anova2rm**  (two-way RM ANOVA). Measurements are repeated in the same subjects across both TIME and GROUP (Injured vs. Uninjured).

2) *Treatment Injured vs Control*:  **spm1d.stats.anova2onerm** (two-way ANOVA with one RM).  Subjects are the same across TIME but different across GROUP (Treatment vs. Control) so there is only one RM factor.

3) *Treatment Uninjured vs Control* (**spm1d.stats.anova2onerm**):  (same as above).

Since there are three separate tests you should probably adopt a correction for multiple comparisons like this:

```Matlab
a = 0.05;  %alpha
nTests = 3;
p_critical = spm1d.util.p_critical_bonf(a, nTests);  %0.01695
```

and then use ```p_critical``` instead of alpha=0.05 in the ANOVA inference. 



**SUMMARY**:   The table in your question above represents a single experiment only if there are 20 Treatment subjects.



Regarding *post hoc* analysis:  **spm1d.stats.anova1_posthoc** is not a function in **spm1d** so I can't comment regarding its validity.  Appropriate *post hoc* procedures depend on the ANOVA design.

Todd

**Comment by gillianweir** [comment]
Hi Todd,

Thanks again for your help. For clarification it is injured vs uninjured so I have taken Case 2 as the path. 

One last question, if I was to run a one-way ANOVA on the injured limb over time (3 points), would the appropriate post hoc test simply then be to use spm1d.stats.ttest2? Or is this not valid either as it assumes each test to be independent? If this is the case, would there be another post hoc test that you would recommend in SPM?

Gill

**Comment by 0todd0000** [comment]
Hi Gill,

Most generally, within-subjects (WS) factors require WS post testing and between-subjects (BS) factors require BS post hoc testing.  WS factors are called "repeated-measures" (RM) in ANOVA and "paired" in t tests.

In your example:  if the same subjects performed at the same three time points then TIME is a WS factor and paired t tests should be used in *post hoc* analysis.  If different subjects performed at each time point then TIME is a BS factor so two-sample t tests should be used in *post hoc* analysis.

Your question regarding independence is a tougher one. At the moment **spm1d** only offers the Bonferroni correction, which assumes independence.  You can use the code snippet in my reply above to compute the critical p value (*p_critical*) across all post hoc tests and then use *p_critical* instead of *alpha* when conducting inference in the *post hoc* t tests.

However, the Bonferroni correction is the most conservative correction possible and as you suggest may not be very accurate when the *post hoc* tests are not totally independent.  Nevertheless, my personal feeling regarding *post hoc* analysis is that anything is fine precisely because the analyses are *post hoc*.  Two important exceptions to this "anything is fine" rule-of-thumb are:  (1) WS and BS factors must be analyzed using WS and BS tests, respectively, and (2) The *post hoc* results mustn't qualitatively disagree with the main ANOVA results;  if they qualitatively disagree then they were conducted improperly.  

Future **spm1d** releases will offer a more automated interface to *post hoc* analyses and also alternatives to the Bonferroni correction.  That new interface should clarify some of these issues and make decision-making somewhat easier.

Todd

**Comment by 0todd0000** [comment]
Hi Gill,
I'll close this issue for now but please feel free to re-open it or to post another issue if anything comes up.
Todd
