### ISSUE TITLE
Canonical Correlation with clinical scores

### ISSUE THREAD

**Issue by crisinma** [0todd0000/spm1dmatlab#44]
Dear SPM1d experts, 

I have kinematic data on which I would like to apply a canonical correlation (with its respective post hoc linear regression analysis) to understand the relation between a clinical scale and the movement patterns. My first question is whether it is correct to perform this analysis with two clinical scales that I have (not simultaneously, but one by one). The first scale is a muscle strength scale that goes from 0-5 (in steps of 0.5) per muscle. I summed up the scores of three muscles, so the scale goes now from 0-15 (also in steps of 0.5). The second scale goes from 0-4 (in steps of 0.5) per muscle, and I also have three muscles, so the summed score would go from 0-12 (in steps of 0.5). I checked whether the data has a normal distribution (see histograms attached), but the Shapiro Wilc and Kolmogorov-Smirnof test state the non-normality of the data. 
I was wondering whether I could run the CCA with this type of data or whether I should transform the data to have a more normal distribution. 

Any help is highly appreciated! 
Thank you very much in advance! 
Regards, 
Cristina

![output](https://cloud.githubusercontent.com/assets/11502722/23511837/d102a590-ff5e-11e6-96bc-ab0ac4b41507.jpg)
![output](https://cloud.githubusercontent.com/assets/11502722/23511790/a2fb1f42-ff5e-11e6-821d-6359a610883a.jpg)

**Comment by 0todd0000** [comment]
Hi Cristina,

I'd recommend trying nonparametric CCA (**spm1d.stats.nonparam.cca**) instead of normalizing the data.  Even when the data do not appear to be normally distributed there is often little qualitative difference between parametric and non-parametric conclusions.  Since non-parametric procedures are valid for all distributions, similar parametric and non-parametric results imply that deviations from normality, if any, are not large with respect to the measured effect.

I'd actually recommend regularly comparing parametric and non-parametric results.  Insofar as those results agree you can be confident that the parametric assumption of normality is a reasonable one.

Todd

P.S.  Future versions of **spm1d**'s CCA will support multivariate independent variables and with that functionality you'll be able to use both scales in a single analysis.

**Comment by 0todd0000** [comment]
Hi again Cristina,
I'll close this issue for now but please feel free to re-open it or to post another issue if anything comes up.
Todd

**Comment by crisinma** [comment]
Sorry that I could not reply, Todd, I was too excited that I could actually perform this analysis. Thanks a lot for your advice! 
Regards, 
Cristina
