### ISSUE TITLE
linear regression and R coefficients

### ISSUE THREAD

**Issue by crisinma** [0todd0000/spm1dmatlab#47]
Dear SPM experts, 

I have conducted some (non parametric) linear regression to look at the impact of a clinical variable on kinematic data during upper limb movements in a group of 60 subjects. I have of course done that with SPM1d. 
After conducting the analysis and looking at the results, I think it is important to report the extent and location of the identified clusters as well as the p values of each cluster. However, in scalar statistics we are also used to report the R² values, which indicates how much of the total variation in the dependent variable can be explained by the independent variable. However, I do not know if obtaining these values (I guess one per data point) is possible with the current version of the software. I think that in brain imaging research, you can obtain the beta maps through the Least Squares method, but I am not sure of how to apply it to my data. 
Would you have any suggestion on this? Would you think that it is important to report it or would you only report the p-values? I checked the paper of the vector field analysis and I see that there is no reference to the R² values for further interpretation. In the clinical field where I work, it would surely be a reviewer´s question: how much of the total variation is your variable explaining the dependent variable? And I would of course like to be able to answer it, or even to address it on the paper already.

Thank you very much in advance for the advice and help! 
Regards, 
Cristina

**Comment by 0todd0000** [comment]
Hi Cristina,

Correlation coefficients can be accessed in the "r" field from parametric regression output like this:

```matlab
>> dataset = spm1d.data.uv1d.regress.SpeedGRF();
>> [Y,x]   = deal(dataset.Y, dataset.x);
>> spm     = spm1d.stats.regress(Y, x);
>> r       = spm.r;       %r continuum
>> r2      = spm.r .^2;   %r-squared continuum
```

The "r" field doesn't exist in non-parametric output because test statistic definitions are much more flexible for non-parametric analysis.  That is, non-parametric procedures generally don't have simple mappings  between test statistics and correlation coefficients like parametric procedures do .

Regarding reporting:
I think it's fine to report correlation coefficients.  I personally find test statistics to be more informative because their range is: [-infinity, +infinity].  Since correlation coefficients have a range: [-1, +1] they tend to plateau near -1 and +1, and thereby have a squashed or compressed appearance as can be seen in the figure below.

Todd


![fig1](https://cloud.githubusercontent.com/assets/4276626/26607813/4a2d71c4-45d3-11e7-9135-015ecdf2aef2.png)

**Figure 1**:  Example regression, t statistic (from ./spm1d/examples/stats1d/ex1d_regression.m)

![fig2](https://cloud.githubusercontent.com/assets/4276626/26607817/4cc956e6-45d3-11e7-81ff-a01d4ab3f1a7.png)

**Figure 2**:  Correlation coefficient corresponding to the Fig.1 analysis.

**Comment by crisinma** [comment]
Hi Todd, 

Thank you very much for the quick and informative answer! (as always :-) )

Regards, 
Cristina
