### ISSUE TITLE
Threshold Detection

### ISSUE THREAD

**Issue by SSMITH204** [0todd0000/spm1dmatlab#5]
Hi Todd,

I am using MatLab to run SPM, when I run a two samples t-test, only the positive threshold is being calculated and applied. On inspection of the graphs the negative values would be significant however there is no negative threshold in order to detect the significance.

I have attached two figures the first of the raw ground reaction force data used being used and the second the t-test output, and below is the code I was using.

![raw plots](https://cloud.githubusercontent.com/assets/7521965/9629083/f2fd0d30-5167-11e5-99a8-39b28eb2baf7.png)
![spm_force](https://cloud.githubusercontent.com/assets/7521965/9629084/f2fff432-5167-11e5-810f-ed9605071d35.png)

yA = C_Force_Raw_Walk;
yB = KOA_Force_Raw_Walk;
spm  = spm1d.stats.ttest2(yA, yB);
spmi = spm.inference(0.05, 'two_tailed', false);
figure('Name','Force_Raw_SPM');
spmi.plot()
spmi.plot_threshold_label();
spmi.plot_p_values();
xlabel('Stance (%)');

Any help would be greatly appreciated.
Kind Regards
Stephanie

**Comment by m-a-robinson** [comment]
Hi Stephanie,

The reason you have no negative threshold is because you calculated the inference for a one-tailed analysis only (spmi = spm.inference(0.05, 'two_tailed', false). If you meant to run a two-tailed analysis then you can change line 4 of your code to:
spmi = spm.inference(0.05, 'two_tailed', true);
this should then calculate (& plot) both the positive and negative thresholds.

If you did mean to calculate one-tailed inference then if you swap the order of yA and yB in the t-test calculation this should then produce a positive t-curve.
spm = spm1d.stats.ttest2(yB, yA);

Regards
Mark

**Comment by SSMITH204** [comment]
Hi Mark,

That's great thank you very much.

Sorry for wasting your time

Best Wishes
Stephanie
