### ISSUE TITLE
effect sizes and r-values

### ISSUE THREAD

**Issue by SinaDavid** [0todd0000/spm1dmatlab#52]
Hi Todd!

I have two (hopefully) quick questions:

-Is there any chance to report effect sizes out of spm results? Some journals request them and I was wondering if it is possible to calculate them? I usually use G-Power for discrete calculations, but probably you have something in mind for spm.

-If I do regression testing, and want to report r-values, how do you do that? I don't want to plot another graph. Do you think it's ok to report a rang of r-values or a mean r-value for the cluster?
 
![untitled](https://user-images.githubusercontent.com/9551718/28860239-049b69b2-775c-11e7-9ef3-3434647a7c03.jpg)
![untitled2](https://user-images.githubusercontent.com/9551718/28860242-06f92474-775c-11e7-9499-5bc50bdba3fe.jpg)

Thanks in advance!
Sina

**Comment by 0todd0000** [comment]
Hi Sina,

Effect sizes are indeed computable, but must be manually computed outside the current version of **spm1d**.  If you're not certain how to do that the please send the test type for which you want to calculate effect size (e.g. two-sample t test) and/or what effect sizes you want to compute.  Alternatively, you could try pre-emptively arguing with the journal that test statistic magnitudes are quite similar to effect sizes, and that the ultimate effect size curves will be qualitatively identical to the reported test statistic curves.

If you'd like to report r values but don't want to report a graph I'd suggest producing the r-value graph as supplementary material and describing it in the text, possibly with range, but it might be sufficient to specify only the r value associated with the maximum t value.  For example, for the data above I might report a maximum r value of about 0.42 at about time=92%;  that should be sufficient to get a sense of how strong the correlation is in the vicinity of the t maximum.

Todd

**Comment by SinaDavid** [comment]
Hi Todd,

Thanks for the quick answer! I already recognized your paper on effect sizes and power analysis in PeerJ and tried to follow up, but as I'm a Matlab user I failed :-) And I generally understand how to compute power and effect sizes for one discrete data point, but I guess the dependency of time points does not allow for multiple calculation. So I would be more than happy if you could assist! I did nonparametric t-testing (group sizes are 48 and 18...) and I want to do post-hoc power analysis as my results showed significance. 

Also thank you for your advice regarding the r-values!

Thank you so much!
Sina

**Comment by 0todd0000** [comment]
Hi Sina,

Post hoc power analysis is not valid so I'd suggest avoiding it.  Power analysis is valid only when conducted before an experiment, based on an effect which one justifies as having a priori importance.  It is not valid to conduct power analysis based on observed effects because experimental effects can be random. 

Will the journal allow you to report test statistic magnitudes instead of effect sizes?

Todd

**Comment by SinaDavid** [comment]
Hi Todd,

Ok, I'm going to talk to them. So would you also not recommend to test effect sizes post-hoc?

Sina

**Comment by SinaDavid** [comment]
Hi again, something just came to my mind when I was re-reading your email: Did you mean that post-hoc analysis is always not valid or just in the special case of SPM calculation? Because, from what I understood, the power tells me how real the chance is to have a beta-error as the result...So, I'm a little confused. 
And sorry for mixing power and effec size, which is of course independent. Are you planning to include that to SPM?

**Comment by 0todd0000** [comment]
Hi Sina,

*Post hoc* power analysis is never valid.  This applies to all hypothesis testing, not just to SPM.

Power is the probability that an experiment will detect an *a priori* effect. *Post hoc* power analysis is invalid because the effect must have been defined before the experiment.  It's a bit like trying to calculate alpha based on an experimental result;  you can't use the results of an experiment to calculate alpha, and you similarly can't use them to calculate beta (i.e. 1 - power).  Both alpha and beta pertain to an infinite set of experiments and are independent of particular experimental outcomes.

Effect size calculations will indeed be supported in future versions of **spm1d**, as will power calculations.  If you'd like to calculate effect sizes manually for a two-sample t test please consider using Cohen's effect size:  (mean difference) / (pooled SD).

Todd

**Comment by SinaDavid** [comment]
Well, that sounds plausible...Thanks for clarifying! 

Best regards,
Sina
