### ISSUE TITLE
Non-parametric anova1rm code?

### ISSUE THREAD

**Issue by CSmythIRE** [0todd0000/spm1dmatlab#55]
Hi all, 

I am trying to run a non parametric repeated measures anova test on a case study with 1 participant, 3 conditions and 10 trials in each condition. 
The code I am currently using is below:

spm       = spm1d.stats.nonparam.anova1rm(Y, A, SUBJ);  %within-subjects model
spmi      = spm.inference(0.05, 1000);

However, I get two errors:

"Error using spm1d.stats.nonparam.snpm.ASnPM1D/inference (line 43)
The value of 'two_tailed' is invalid. It must satisfy the function: islogical.

Error in Upstart_SPM_nonparametricRMANOVA_analysis_MSc (line 21)
spmi      = spm.inference(0.05, 1000);"

I cannot get this code to work, regardless if I have  'iterations = ' within the code or change the iteration number. 

Any ideas why this code will not work?

Thank you in advance, 
Carol

**Comment by 0todd0000** [comment]
Hi Carol,

Thank you very much for reporting this issue!  I confirm that I can reproduce the problem.

Fortunately there is an easy solution:  please specify the number of iterations using a name/value pair like this:

```matlab
spmi = spm.inference(0.05, 'iterations', 1000);
```

That should solve the problem.  Although this solution is easy, the error message is indeed difficult to understand.  I'll adjust the error message so that it reports something more meaningful and I'll write to you again once the software is updated at GitHub.com.

Todd

**Comment by CSmythIRE** [comment]
Hi Todd, 

This solved the problem. Thank you for your help. 

Carol
