### ISSUE TITLE
Normality tests

### ISSUE THREAD

**Issue by burniel** [0todd0000/spm1dmatlab#56]
I have been using SPM to compare EMG data from muscles during sprint cycling from 2 sessions. The EMG data has been normalised to % of crank cycle. I have attached a normality plot for one of the muscles, only small sections of the data exceed the threshold for normality. Should I be using non-parametric SPM or because only small sections of the data (about 10% of the crank cycle) violate the assumption of normality could I use parametric SPM?

[Normality plot.docx](https://github.com/0todd0000/spm1dmatlab/files/1251707/Normality.plot.docx)

**Comment by 0todd0000** [comment]
As a rule of thumb I'd suggest always conducting both parametric and non-parametric analyses and comparing the results.  Insofar as the results agree the parametric approach's assumption of normality is a reasonable one.  If the results qualitatively disagree then it would be important to understand why by examining the data a little more closely.

In this particular case the (non-) normality results do indeed reach significance, but that does not necessarily imply that the data are non-normal.  Strictly speaking the results indicate only that perfectly normal data would, due to random sampling, produce results like this relatively rarely.  Moreover, a slightly different registration (i.e. time normalization) procedure may reduce variability and drive the data toward normality.  Data smoothing would do the same.

Todd
