### ISSUE TITLE
Multiple trials for vector field analysis

### ISSUE THREAD

**Issue by GuillaumeRao** [0todd0000/spm1dmatlab#58]
Dear Todd, 
I was wondering whether it was possible to perform a vector field analysis (hotellings paired) using input data from multiple trials per subjects and conditions instead of average data for each subject ? 
Thanks a lot !
Best regards, 
Guillaume

**Comment by 0todd0000** [comment]
Hi Guillaume,

A paired Hotelling's test can only test paired observations (i.e. one observation or one mean observation per subject) so it is not possible to incorporate both within- and between-subject variance in a paired Hotelling's test, just like it is not possible to incorporate both sources of variability in a paired t test.

Usually trials cannot be paired individually (i.e. Trial 1 for Subject 1 in Session A cannot be logically paired with Trial 1 for Subject 1 in Session B because trials are random samples from Subject 1's population of trials), so it is usually not possible to regard TRIAL as pairable.  In most Biomechanics applications it is suitable to use only within-subject means (rather than using all observations) because between-subject variance is usually much larger than within-subject variance, implying that ignoring within-subject variance is usually justifiable.

So I'd recommend using only within-subject means unless you have an experimental question that pertains specifically to within-subject variance.

Todd

**Comment by GuillaumeRao** [comment]
Hi Todd, 
thanks a lot for this reply which makes perfect sense, I'll stick to within-subjects means !
Have a nice day, 
Guillaume
