### ISSUE TITLE
input format for anova2onerm in matlab

### ISSUE THREAD

**Issue by adrianrivadulla** [0todd0000/spm1dmatlab#62]
Hi there,

First of all I'd like to say congrats and thanks for this forum as it's being very useful. I'm trying to run an ANOVA with a between subjects factor Group (2 groups) and a within subjects factor Test (pre-test, post-test, retention and transfer tests). After reading the documentation, I've defined a variable (hip flex angle, I've got my concerns on whether I should be using SPM with angles due to their circular nature but that's another discussion out of the aim of this post) which is a 64x1001 matrix, where 64 is the number of trials (1 trial per participant per test 16x4), a group_code variable (64x1 vector of 1s and 2s), a test_code (64x1 vector of 1s 2s 3s and 4s) and a participant_code variable (64x1 vector of numbers ranging between 1 and 16). When I try to run the anova2onerm function I get a warning saying only one observation per participant found and no more results than the effects to be found (A, B and AxB).

I'm pretty sure I'm doing something wrong with the input format, could you please shed some light on this for me?

Thanks a lot for your attention, I'm looking forward to your response.

Adrian

**Comment by 0todd0000** [comment]
Hi Adrian,

Thank you for the positive feedback!

 > I've got my concerns on whether I should be using SPM with angles due to their circular nature

Problems can arise only if (a) angular changes and/or angular variability is very large (more than 180 deg) or (b) the datum and angle amplitudes are defined poorly (i.e. neutral is 0 deg, 5 deg flexion is "+5 deg" and 5 deg extension is "+355 deg").  Since most human joints have small ranges of motion (a) is not usually a problem.  If you use follow established ISB guidelines then (b) is not typically a problem either.

> When I try to run the anova2onerm function I get a warning saying only one observation per participant found

This warning means only that there is one observation per particpant and per condition, which in turn implies that the model residuals are null.  In other words, repeated-measures ANOVA models contain terms for each particpant and each condition, and after fitting all of those terms to the data there is no residual variability remaining.  SPM uses residuals to estimate one-dimensional smoothness, so the warning indicates that smoothness will be estimated using pseudo-residuals, which are computed for each subject and averaged across subjects. Please see related discussions in spm1d's Python forum here:
https://github.com/0todd0000/spm1d/issues/43
https://github.com/0todd0000/spm1d/issues/49

Todd
