### ISSUE TITLE
problem running example stats1d ex1d_ttest2.m

### ISSUE THREAD

**Issue by stepvalen** [0todd0000/spm1dmatlab#65]
Hi there, 
I am new to spm1d and a novice MATLAB user, so I am hoping my problem will be simple to fix if someone could point me in the right direction.  When I run the example script stats1d ex1d_ttest2.m, I get the following error:
NOTE: Setting "force_iterations" to "true" may require substantial computational resources and may cause crashes. USE WITH CAUTION.
Error in spm1d.stats.nonparam.snpm.ASnPM1D/inference (line 50)
           self.permuter.check_iterations(alpha, iterations, force_iterations)
Error in ex1d_ttest2 (line 18)
spmi      = spm.inference(0.05, 'two_tailed',true, 'interp',true);

any ideas on how I can troubleshoot this problem? When I % the problematic line ('self.permuter.check_iterations(alpha, iterations, force_iterations)'), the script works, although I do not get the expected answers (different p-values etc from those in the online handouts for the same dataset and statistical test), although the plot looks the same. I am really keen to get started with spm1d, and looking forward to be able to apply it to my own data. 
many thanks!
steph

**Comment by 0todd0000** [comment]
Hi Steph,

Thank you for reporting the problem, and apologies that the error message is not easier to understand!

It sounds like the problem is being caused by an attempt to run too many iterations, which would take hours (or days, weeks, years or even centuries) to complete, depending on how many iterations there are. As a quick fix please try setting `iterations` to a relatively small value, like 100 or 1000 as follows:

```matlab
iterations = 1000;
snpm       = spm1d.stats.nonparam.ttest2(yA, yB);
snpmi      = snpm.inference(alpha, 'two_tailed', two_tailed, 'iterations', iterations);
```

That should get rid of the error message.

Also, this is one of **spm1d**'s non-parametric procedures, which uses random permutations to conduct statistical inference, so results will only be precisely reproducible if you control the random number generator state using MATLAB's `rng` function.  Different `rng` states (e.g. `rng(0)` vs. `rng(15)`) are expected to produce numerically different, but not qualitatively different results.  If they produce qualitatively different results then the number of permutations is probably insufficiently small.

Todd
