### ISSUE TITLE
Circular Data

### ISSUE THREAD

**Issue by gillianweir** [0todd0000/spm1dmatlab#66]
Hi Todd,

Hope you are well. 
I am just writing as we have a few data sets looking at lower limb coordination using a vector coding technique. When we calculate coupling angles using this technique we get values ranging from 0 to 360 degrees and use circular statistics to calculate means, SDs etc. So I wondered, is there the potential to integrate circular means/SDs into SPM?

Just in case you aren't familiar with the sort of output from vector coding I have just attached a reference below which shows it quite nicely. 

Needham, R. A., Naemi, R., & Chockalingam, N. (2015). A new coordination pattern classification to assess gait kinematics when utilising a modified vector coding technique. Journal of biomechanics, 48(12), 3506-3511.

Thanks,
Gill

**Comment by 0todd0000** [comment]
Hi Gill,
Thank you very much for this point. I'm pretty sure that circular statistics can be integrated with SPM, but I'm not certain whether a parametric solution would be straightforward. Regardless, I agree that circular data analysis capabilities would be useful.  For now I've added this to **spm1d**'s roadmap page here:
https://github.com/0todd0000/spm1d/issues/45
Perhaps a public version will be ready within one year. If you need this before then let me know.
Todd

**Comment by gillianweir** [comment]
Hi Todd,
Thanks so much for the quick reply. I wondered whether this was something we could try and work on from our end and check with you - as in something on the surface inputting circ mean and SDs into the code or is it something more complex best left to you?
Thanks,
Gill

**Comment by 0todd0000** [comment]
Hi Gill,

It should be possible to get a non-parametric procedure up and running quickly.  As you suggest I think the circular mean and SD could be used in a test statistic calculation, then non-parametric inference could be conducted just like for a normal t test.  

A parametric test would take longer to get working. It wouldn't be valid to substitute the circular mean and SD into the existing parametric procedures because the underlying distribution is different than the standard t distribution. The hardest parts would be: (i) computing appropriate probability distributions for 1D data using random field theory, then (ii) validating those probability distributions by simulating random 1D circular data.  The former might be a trivial extension of existing random field theory distributions, but I'm not sure.  The latter might be tough; I'm not aware of any software that exists for simulating 1D circular data, so it might take a while to get an appropriate random number generator built.  I'd estimate one to four weeks of fairly solid work to get things validated properly for arbitrary t tests, with arbitrary sample sizes, variances and 1D smoothness.

But parametric procedures don't need validation, so I'd recommend starting there if you need something quick.

Todd
