### ISSUE TITLE
Anova2onerm

### ISSUE THREAD

**Issue by NicolasFlores14** [0todd0000/spm1dmatlab#68]
Hello Todd,

I was performing a two-way ANOVA with the factor A in between-subject and the factor B in within-subject with "anova2onerm".

For several reasons, before the "anova2onerm", I had performed a one-way repeated measures ANOVA to assess the effect of the previous factor B with "anova1rm". I have observed that the critical threshold value with "anova1rm" on factor B (9.061) was identical to the critical threshold value with "anova2onerm" on factor B (9.061). The test statistic field SPM{F} was also identical between both procedures, thus providing identical significant results for the factor B.

Thus, I tried to perform an ANOVA on factor A with "anova1" to check if I found an identical result than the "anova2onerm" on factor A. With "anova1" the critical threshold value on factor A (4.773) was different from the critical threshold value obtained with "anova2onerm" on factor A (6.898). With "anova1", the test statistic field SPM{F} of factor A exceeded substantially the critical threshold up to 50, while with "anova2onerm", the test statistic field SPM{F} of factor A did not exceed the 6.898 critical threshold.

To understand the differences between all these procedures, I would like to know if you have any idea/explanation to the identical results on factor B (anova2onerm vs. anova1rm), and the different results on factor A (anova2onerm vs. anova1).

Thanks for your answer,
Best regards.

Nicolas

**Comment by 0todd0000** [comment]
Hi Nicolas,

For 0D data the critical F value (F*) is determined by the degrees of freedom (DF), so if the DF are the same in the two models, F* will also be the same.  For 1D data the situation is more complex because F* also depends on 1D smoothness.

Before considering your questions in detail I'd like to understand how the DFs are identical between the two models. Please send your values for:

- *N* = total number of responses,  ```numel(A)```
- *nA* = number of A groups,    ```numel( unique(A) )```
- *nB* = number of B groups,   ```numel( unique(B) )```
- *nS* = number of subjects,    ```numel( unique(SUBJ) )```
- *nReps* = number of repetitions of each AB combination for each subjects
- *FWHM* (for **anova2onerm**) - the smoothness value from the first model, ```spm.fwhm```
- *FWHM* (for **anova1rm**) - the smoothness value from the second model,  ```spm.fwhm```

**Comment by NicolasFlores14** [comment]
Hello Todd,

Thanks for your answer. Please find the details below:

N = 380,
nA = 3,
nB = 2,
nS = 19,
nReps = Note that the A factor is 3 groups of different participants. Each of the 19 participants has performed the two levels of B factor 10 times,
FWHM (for anova2onerm) = 37.8339,
FWHM (for anova1rm, factor B) = 37.8339,
FWHM (for anova1, factor A) = 43.4848.

Nicolas

**Comment by 0todd0000** [comment]
Hi Nicolas,

With those counts I can understand a threshold of 9.061 for **anova1rm**, but the threshold should be lower (about 7.7) for **anova2onerm**.  Please double-check the **anova2onerm** threshold.  If it is indeed 9.061, please send complete display results for the two cases like this:


**anova2onerm**
```
FF = spm1d.stats.anova2onerm(Y, A, B, SUBJ);
FFi = spmlist.inference(0.05);
FBi = FFi('B');
disp(FBi)
```

**anova1rm**
```
spm       = spm1d.stats.anova1rm(Y, B, SUBJ);
spmi      = spm.inference(0.05);
disp(spmi)
```

**Comment by NicolasFlores14** [comment]
Hello Todd,

Below, the complete display results: 

**anova2onerm** (factors A, B and AB)
_Factor A:_
SPM{F} inference
      effect: 'Main A'
           z: [1×101 double]
          df: [2 16]
        fhwm: 37.8339
      resels: [1 2.6431]
       alpha: 0.0500
       zstar: 6.8983
    h0reject: 0
       p_set: NaN
           p: []

_Factor B:_
SPM{F} inference
      effect: 'Main B'
           z: [1×101 double]
          df: [1 16]
        fhwm: 37.8339
      resels: [1 2.6431]
       alpha: 0.0500
       zstar: 9.3905
    h0reject: 1
       p_set: 0.0065
           p: 0.0065


**anova1rm** (on factor B)
SPM{F} inference
      effect: 'Main A'
           z: [1×101 double]
          df: [1 18]
        fhwm: 37.8339
      resels: [1 2.6431]
       alpha: 0.0500
       zstar: 9.0614
    h0reject: 1
       p_set: 0.0075
           p: 0.0075

Nicolas

**Comment by 0todd0000** [comment]
From the output above it would appear the the critical thresholds (zstar) are actually different (9.3905 and 9.0614).  Does this solve the problem?

**Comment by NicolasFlores14** [comment]
Hello Todd,

Yes, there are slightly different, maybe I made an error when I had read the previous critical threshold.

On factor A, the substantial difference between **anova1** and **anova2onerm** outputs came from another error from me. Can you confirm me that I have to input the mean of all trials per participant rather than all trials?

Thanks for your answers,
Best regards.

Nicolas

**Comment by 0todd0000** [comment]
Hi Nicolas,

No problem about the threshold.  They are quite close!

Regarding use of (1) within-subject means vs. (2) all trials:
- The F statistics for (1) and (2) should be identical.
- The degrees of freedom for (1) and (2) should be identical.
- In **spm1d** the estimated smoothness (FWHM value) for (1) and (2) might be slightly different. The FWHM estimate is slightly better for (2) because the smoothness of all trials are considered, not just the smoothness of the means.
- Small FWHM changes cause small changes in the critical threshold (F*).  However, those changes should be quite small, and shouldn't affect the final results qualitatively.
- If you observe a qualitative change when using means vs. all trials please contact me!!!

Todd
