### ISSUE TITLE
constant p values in non-parametric analysis

### ISSUE THREAD

**Issue by PouyanMehryar** [0todd0000/spm1dmatlab#69]
Hi Tod, 

Summary: Recorded EMG from population A and B at different speeds,

I have performed both non-parametric and parametric paired-Hotelling's T2 test using a Bonferroni correction to compare between speeds for each population. One thing that I noticed is that all the p-values calculated from the non-parametric SPM have the value of 0.005. That is, any suprathreshold clusters above the T2* have the same probability i.e. p= 0.005 for all muscles.
 It is worth mentioning that I have used 200 permutations however, the nTest was varied between 3 and 9 depending on the hypotheses. In both cases, the p-value of 0.005 was obtained. 

Q1) Is this normal? why is that?

Q2A) Have the p-values stated, where the suprathreshold clusters occurred in the graph, already been corrected? If not what do those p-values represent?
 
Q2B) Do I need to compute the correct p-value everytime that I implement Bonferroni correction regardless of what tests (multivariate (paired Hotelling's), univariate (paired t-test) or 0D, 1D) have been implemented? 

Q2C) Is there a way to incorporate a piece of code to have the corrected value stated in the graph??

Thanks in advance for your response!

**Comment by 0todd0000** [comment]
Q1)  This is normal, but only if you use too few permutations. In permutation-based non-parametric inference the minimum p value is ```1/np```, where ```np``` is the number of permutations, so if ```np=200```, the smallest possible p value is 0.005. I'd recommend using at least ```np=1000```, but ```np=10000``` is preferable to ensure both numerical stability and more accurate p values.  If you use ```np=200```, the critical test statistic value will likely change if you change the initial randomization state (the randomization state can be set using MATLAB's built-in ```rng``` function).  The critical test statistic value generally becomes increasingly stable as ```np``` increases.  As a general rule-of-thumb, always try different randomization states (e.g. ```rng(0)```, then ```rng(1)```, then... ```rng(4)```) and check the results for each state.  If the results change qualitatively you should use more permutations. If you use ```np=10000``` the constant p value issue will no longer be a problem because the minimum p value would be 0.0001, which is ten-times smaller than the typically smallest reported p value of p=0.001.

Q2A)  The p values are not corrected. They are computed based on the alpha value you input, and the maximum possible p value is always alpha.  To compute corrected p values you need to perform the inverse of the Bonferroni correction as described at the bottom of the following page:
http://www.spm1d.org/doc/PostHoc/anova.html

Q2B) Yes.  Until **spm1d** supports *post hoc* analysis you need to manually perform all *post hoc* procedures, including computing corrected p values.

Q2C) There are two options.  One option is to not use the built-in ```plot_p_values``` function and instead write your own function for plotting p values.   A second option is to change the p values in the SPM structure, before calling ```plot_p_values``` like this:
```matlab
% STEP 1:  Compute corrected threshold
alpha  = 0.05;  %family-wise Type I error rate
nTests = 3;     %number of post hoc tests
p_crit = spm1d.util.p_critical_bonf(alpha, nTests); %critical p threshold

% STEP 2:  Run one of the post hoc tests using the corrected threshold
spm    = spm1d.stats.ttest2(yA, yB);
spmi   = spm.inference(p_crit);

% STEP 3:  Compute corrected p values for each upcrossing
n      = numel( spmi.p ); %number of upcrossings
p_corr = zeros(1,n);      %corrected p values
for i=1:n
    p_corr(i) = spm1d.util.p_corrected_bonf(spmi.p(i), nTests);
end
spmi.p = p_corr;  %copy the corrected p values into the SPM structure

% STEP 4:  Plot (with corrected p values)  
spmi.plot();
spmi.plot_threshold_label();
spmi.plot_p_values();
```

**!!!Note!!!**
The Bonferroni procedure implemented in the code above is not strictly correct, and is generally too conservative.  Until *post hoc* analysis becomes an official feature of **spm1d** it is not possible to support alternative *post hoc* analyses in this forum.

**Comment by PouyanMehryar** [comment]
Hi Tod, 

Q2C) I implemented the above code, however, the incorrect p-values still being produced. 
I am not sure what could be wrong?

Thanks!

**Comment by 0todd0000** [comment]
Oops!  Sorry about that!  The ```plot_p_vaues``` function uses p values from the cluster structures, so please also change the cluster structures like this:

```matlab
spmi.clusters{i}.P = p_corr(i);
```

Here is the complete code snippet:

```matlab
% STEP 1:  Compute corrected threshold
alpha  = 0.05;  %family-wise Type I error rate
nTests = 3;     %number of post hoc tests
p_crit = spm1d.util.p_critical_bonf(alpha, nTests); %critical p threshold

% STEP 2:  Run one of the post hoc tests using the corrected threshold
spm    = spm1d.stats.ttest2(yA, yB);
spmi   = spm.inference(p_crit);

% STEP 3:  Compute corrected p values for each upcrossing
n      = numel( spmi.p ); %number of upcrossings
p_corr = zeros(1,n);      %corrected p values
for i=1:n
    p_corr(i) = spm1d.util.p_corrected_bonf(spmi.p(i), nTests);
    spmi.clusters{i}.P = p_corr(i); %also adjust the cluster structures' p values 
end
spmi.p = p_corr;  %copy the corrected p values into the SPM structure

% STEP 4:  Plot (with corrected p values)  
spmi.plot();
spmi.plot_threshold_label();
spmi.plot_p_values();
```

**Comment by PouyanMehryar** [comment]
Hi Tod, 
My question is related to the normalization of the data and I thought to post this to help others with a similar question
Study: lower limb amputees generally walk slower with longer stance phase and shorter swing phase than their able-bodied counterparts during the normal self-selected waking condition. 
The SPM comparison between the two groups shows triceps surae follows the shift as compared to the healthy subjects when the whole gait cycle is normalized to 101 points. 
1a) Would there be a difference between the SPM results of the two groups if the normalization was done for the stance phase and swing phase separately than the whole gait cycle.  
1b) I understand that we shall not change the a priori hypothesis of the study but I’d like to know will the phase shift in the triceps surae of the amputees (where suprathreshold cluster occurs) could be adjusted and produce different results if the gait cycle is divided up to two phases (stance and swing phase) rather than considering the whole gait cycle normalization?

**Comment by 0todd0000** [comment]
H Pouyani, thank you for this post. The content is somewhat unrelated to the content above, so I've create a new issue here:  #115
Todd
