### ISSUE TITLE
h0reject vs. p value

### ISSUE THREAD

**Issue by NicolasFlores14** [0todd0000/spm1dmatlab#71]
Hello Todd,

I performed a non-parametric paired t-test on my data. The alpha level is set to 0.05. The output of the t-test is as below:

SnPM{t} inference (0D)
              z: -1.3957
    nPermUnique: 8
    nPermActual: 8
          alpha: 0.0500
          zstar: [-1.3181 1.3181]
     two_tailed: 1
       h0reject: 1
              p: 0.1250

Do you have any explanation concerning the rejected h0, while the p value is greater than the alpha level?

Thanks for your answer,
Best regards.

Nicolas

**Comment by 0todd0000** [comment]
Hi Nicolas,

The problem is that the sample size is too small.

The minimum p value is 1/nPerm, where nPerm is the number of permutations used. Since nPerm=8 in this case, the minimum p value is 1/8 = 0.125.  To get a p value of 0.05 or lower there must be at least nPerm=20.

For one-sample and paired tests there are 2^N unique permutations, where N is the number of observations.  In this case it would appear that N=3 (sample sizes that small are usually too small for meaningful inference, because neither the population mean nor the population variance can be accurately estimated). If you increase N to 5 or larger you will be able to see p values smaller than 0.05.

Todd

**Comment by NicolasFlores14** [comment]
Hello Todd,

Thank you. 

Effectively, the sample size is small in this specific case. Even if I can't observe a p-value lesser than 0.125, does it mean h0 is effectively rejected here and I observe a difference (knowing the meaningful is small)?

Thanks again.

Nicolas

**Comment by 0todd0000** [comment]
I would interpret the result as follows:
- The minimum p value that can be inferred is 1/8. Thus this method can't be used to test a hypothesis with alpha=0.05.
- Parametric inference could be used to obtain an arbitrarily low p value, but the parametric result would similarly suffer from problems related to the small sample size.
