### ISSUE TITLE
Single-subject data

### ISSUE THREAD

**Issue by Hamedhn** [0todd0000/spm1dmatlab#78]
Hi everyone,

I have a dataset containing Ligament Elongation for 3 Groups of TKA subjects (the type of implant was different between Groups). We had 10 patients in each Group who performed 5 cycles of 3 different activities (Level gait, downhill Walking and stair descent). I want to statistically test whether the Ligament Elongation during a single activity is different between different Groups (implant types). Also for a single Group I want to see whether the Ligament Elongation is different between different activities or not (of Course this Needs to normalise the Ligament Elongation to the knee Flexion angle). My main question is how to include the repetitions in the test. 
What statistical test do you recommend?

Thanks in advance,
Hamed

**Comment by 0todd0000** [comment]
Hi Hamed,

{Please note that this discussion pertains to analysis in general, and not specifically to SPM}

Provided each subject performed all three tasks, I think a one-way RM ANOVA is appropriate (**spm1d.stats.anova1rm**). 

Regardless of the design, you may need to consider whether the repetitions violate assumptions of independence.  All tests assume that: (1) repetitions have been randomly sampled from the population of all repetitions, and that (2) the samples are independent.

Regarding (1): this is analogous to selecting students from one's lab or department rather than randomly sampling students from all labs in the city or country or world.  This is not a perfectly random sample, and is usually referred to as a convenience sample. Convenience samples are generally acceptable in fundamental Biomechanics studies because the alternative --- a truly random sample --- is usually too expensive.  Convenience samples are usually not acceptable in intervention and other medical studies.

Regarding (2): the easiest way to avoid dependence is to randomize the order in which the activity repetitions are performed. If you did not randomize the order (e.g. if the subjects performed five repetitions of Activity 1, then five of Activity 2, then five of Activity 3), then there is a danger that other factors --- usually referred to as nuisance factors --- can affect the results.  One way to model and partially control for nuisance factors is described in the GLM section here:
http://www.spm1d.org/doc/Stats1D/onetwosample.html#general-linear-model-glm
In this example, note that both linear drift (e.g. fatigue) and sinusoidal drift (e.g. electrical equipment drift) are included as nuisance factors.  However, please note that nuisance factor modeling is not  officially supported in **spm1d**.

Todd
