### ISSUE TITLE
Resels

### ISSUE THREAD

**Issue by meteor77** [0todd0000/spm1dmatlab#79]
Hi Todd,

I came across the "resel" factor in my results and as I was reading your description of it I kinda got confused about the second number it generates. Would you mind elaborating on it? and would it also be possible to see the p values if the results are not significant as well?

**Comment by 0todd0000** [comment]
Sorry for my delayed reply!! Thank you for the reminder.

Similar to "pixel" and "voxel", which mean "picture element" and "volume element", respectively, "resel" means "resolution element". Unlike pixels and voxels, which describe image size, resels describe the resolution (or smoothness) of the measured continuum process.  For 1D continua there are are two resel counts:

1. The number of unbroken segments.  In most cases this is one. The only exception is if one or more gaps exist in the data (e.g. flight phase in ground reaction forces during jumping).

2. The number of smoothness-normalized processes. This is defined as (continuum size / FWHM), where FWHM is the smoothness estimate, and where continuum size is Q-1 (if Q is the number of continuum nodes).  This is effectively an estimate of the number of independent processes in the 1D continuum.  As the data become smoother, this resel count approaches 1.  As the data become rougher, this resel count approaches Q.

These resel counts are stable to sampling frequency changes provided one measures the data above the Nyquist criterion.

Regarding p values:

- I have added this to the list of feature requests here:  https://github.com/0todd0000/spm1d/issues/45

- P values greater than alpha do not yet appear in **spm1d** because their computation is difficult.  Parametric p values less than about 0.2 are quite accurate, but they generally become less accurate as they become larger.  There are some numerical work-arounds which will yield approximately accurate p values, but the p values will not be sufficiently accurate for certain types of analyses, like Bayesian inference.


I'm happy to discuss further if anything is unclear, sorry again for missing your previous post!

Todd
