### ISSUE TITLE
unbalanced two-way ANOVA

### ISSUE THREAD

**Issue by kpchad** [0todd0000/spm1dmatlab#81]
I'm trying to perform a two-way ANOVA in Matlab:

spmlist   = spm1d.stats.anova2(Y, A, B);

but get an error that it must be balanced:

**Error using spm1d.stats.anova.designs.ANOVA2/check_balanced (line 48)
Design must be balanced.**

my A and B are the same size, but the groupings within each of these factors are of different sizes. Is the package able to deal with an unbalanced situation like this?

Thanks

**Comment by 0todd0000** [comment]
Unfortunately **spm1d** can currently only handle unbalanced one-way ANOVA. One way around this issue is to artificially impose balance on your design by randomly removing data from the larger group(s), then repeating for a number of random data removals.  If there are no qualitative changes in the ANOVA results you can be reasonably sure that unbalanced analysis would produce similar results.

Implementing support for unbalanced design is near the top of the list of features to be implemented next:
https://github.com/0todd0000/spm1d/issues/45

**Comment by kpchad** [comment]
Ok thanks for clarifying and for the work-around suggestion!
