### ISSUE TITLE
Shapiro-Wilk Normality Tests

### ISSUE THREAD

**Issue by JessicaTucceri** [0todd0000/spm1dmatlab#86]
Is it possible to conduct a Shapiro-Wilk test for normality? 

When I look inside my toolbox, (spm1d_matlab/spm1d/stats/normality/) it appears that all of the files are using the k2residuals files. And I am unable to find the swresiduals files. 

When I run a normality test using the sw residuals as follows:
```
function [SPM] = anova1rm(y, A, SUBJ)
spm   = spm1d.stats.anova1rm(y, A, SUBJ, 'force_approx0D', true);
SPM   = spm1d.stats.normality.swresiduals( spm.residuals );
```

I receive an error message:

> Error in spm1d.stats.normality.anova1rm (line 7)
> SPM   = spm1d.stats.normality.swresiduals( spm.residuals );
> 
> Error in Normality_anova_test_anklepower_RM (line 11)
> spm       = spm1d.stats.normality.anova1rm(y, A, SUBJ);

But the same is not true for the k2 residuals: 
```
function [SPM] = anova1rm(y, A, SUBJ)
spm   = spm1d.stats.anova1rm(y, A, SUBJ, 'force_approx0D', true);
SPM   = spm1d.stats.normality.k2residuals( spm.residuals );
```

This is the code that I am using:
```
%(0) Load data:
dataset    = spm1d.data.uv1d.anova1rm.ADAnklePowerAllDataFbkRM();
[y,A,SUBJ] = deal(dataset.Y, dataset.A, dataset.SUBJ);

%(1) Conduct normality test:
alpha     = 0.05;
spm       = spm1d.stats.normality.anova1rm(y, A, SUBJ);
spmi      = spm.inference(0.05);
disp(spmi)

%(2) Plot:
close all
figure('position', [0 0  1200 300])
subplot(121);  plot(y', 'k');  hold on;  title('Data')
% subplot(132);  plot(spm.residuals', 'k');  title('Residuals')
subplot(122);  spmi.plot();  title('Normality test')
```

Please let me know if there is something that I need to adjust in my methodology!

All the best, 
Jessica Tucceri

**Comment by 0todd0000** [comment]
Hello Jessica,

It is indeed possible to compute the Shapiro-Wilks statistic as an indicator of (non-)normality, and your code for doing so looks fine. For normality hypothesis testing we've found that the D'Agostino-Pearson K2 statistic works best, partly because it is sensitive to most types of deviations from normality.

In your script everything looks fine, so I'm not sure exactly what is causing there error. Here are two points to consider:

- The dataset `ADAnklePowerAllDataFbkRM` is not available in **spm1d** so appears to be a custom add-on.

- The example script `./examples/normality/1d/ex1d_anova1rm.m` appears to run fine without errors.

So I expect that the problem might exist in the custom dataset. Please first check whether you can run the built-in example script. If that's fine then try checking the dataset and residuals for problems (e.g. missing data, repeated observations, zero variance, etc.). If you can't find the source of the problem, please send the entire error message to give more clues about what might be causing the problem.

Cheers,
Todd

**Comment by JessicaTucceri** [comment]
Hello Todd, 

After running the example script, this is the full error message I receive:

> Warning: Only one observation per subject found.  Residuals and inference will be
> approximate. To avoid approximate residuals: (a) Add multiple observations per subject and
> per condition, and (b) ensure that all subjects and conditions have the same number of
> observations. 
>  >In spm1d.stats.anova.designs.ANOVA1rm/check_for_single_responses (line 33)
>   In spm1d.stats.anova1rm (line 13)
>   In spm1d.stats.normality.anova1rm (line 6)
>   In ex1d_anova1rm (line 13) 
> 
>Undefined variable "spm1d" or class "spm1d.stats.normality.swresiduals".
> 
> Error in spm1d.stats.normality.anova1rm (line 7)
> SPM   = spm1d.stats.normality.swresiduals( spm.residuals );
> 
> Error in ex1d_anova1rm (line 13)
> spm       = spm1d.stats.normality.anova1rm(y, A, SUBJ);

Any clue as to what the problem might be? 

Thanks!
Jessica

**Comment by 0todd0000** [comment]
Hi Jessica, thank you for sending the error message and sorry for the delay. The following line clarifies the problem:

> Undefined variable "spm1d" or class "spm1d.stats.normality.swresiduals".


This indicates that there is no function called **swresiduals**.  (I missed this point in your code above, sorry about that!)  You can find the available functions (.m files) in the following folder:

./spm1dmatlab/+spm1d/+stats/+normality/

You'll notice that there is a **k2residuals.m** file but not a **swresiduals.m** file. So the following command should work:

```MATLAB
SPM = spm1d.stats.normality.k2residuals( spm.residuals );
```

I'd recommend using the D'Agostino-Pearson K2 statistic (**k2residuals**) and not the Shapiro-Wilk statistic for the reasons mentioned in my post above.  If you really need to compute the Shapiro-Wilk statistic it can be computed in the Python version of **spm1d** using the function **spm1d.stats.normality.sw.residuals**.

Todd

**Comment by JessicaTucceri** [comment]
Alright, thanks for the clarification!! 

Jessica
