### ISSUE TITLE
Suprathreshold cluster - minimum size to be considered significant?

### ISSUE THREAD

**Issue by burniel** [0todd0000/spm1dmatlab#90]
I have been reading a paper (see reference below) that used SPM, and they considered a cluster was only significant if larger than 5 nodes as clusters of less than 5 nodes were unlikely to be meaningful. Do I need to consider the size of the cluster, when deciding if it is significant and meaningful?

Colyer, S. L., Nagahara, R., & Salo, A. I. (2018). Kinetic demands of sprinting shift across the acceleration phase: Novel analysis of entire force waveforms. Scandinavian Journal of Medicine & Science in Sports,

**Comment by 0todd0000** [comment]
This is an interesting issue, but one that is difficult to answer definitively. As a brief response I'd say: try analysis both with and without a cluster size threshold, then compare the results. A more detailed consideration follows...

As in Coyler et al. (2018), it is indeed possible to set a minimum cluster size **s** and to ignore clusters whose sizes are smaller than **s**.  The theoretical framework is described in Friston et al. (1994). This is analogous to choosing a threshold height **u**, and ignoring all parts of the SPM that fail to exceed **u**.  The main difference is that **u** is computed from 𝛼, which has direct probabilistic meaning, and whose default value is generally accepted to be 0.05.  Choosing **s** requires either (a) a second probability threshold, like 0.01, or (b) a non-probabilistic threshold based on some other scientific rationale. 

Friston KJ, Worsley KJ, Frackowiak RS, Mazziotta JC, Evans AC. Assessing the significance of focal activations using their spatial extent. Human brain mapping. 1994;1(3):210-20. 
https://doi.org/10.1002/hbm.460010306

In Coyler et al. (2018) the authors state that "clusters of fewer nodes were considered unlikely to be meaningful", so have explicitly provided both an **s** value and a brief justification for it. However, I don't think they completely ignored clusters with smaller **s**, they simply didn't highlight those clusters in the figures.

In Neuroimaging, **s** can be justified based on known brain structure volumes, or on the basis of known physiology. If it is known, for example, that the minimum volume of detectable blood saturation change is 5 x 5 x 5 mm, then one should ignore clusters that are smaller than this because they are likely to be noise. Similarly, if one has a hypothesis regarding a brain structure that is known to have a minimum activation volume of 5 x 5 x 5 mm, then one should probably ignore smaller clusters.

I am unaware of similar rationale in Biomechanics, but it is conceivable that such rationale exist. For example: when the data are force trajectories, clusters correspond to impulse effects, and it might be justifiable to use an impulse threshold for **s** if it can be experimentally or theoretically shown that smaller impulses have negligible effects on the behavior of interest.

Regardless, it would probably be best practice to use **s**=0, and optionally also apply a larger **s**, and then consider the effects on one's conclusions. If the conclusions change qualitatively then it may be important to report the reasons for these changes. This could be especially important in situations where only small clusters exist (i.e. size < **s** for all clusters), because it would change the null hypothesis rejection decision.
