### ISSUE TITLE
'NaN'

### ISSUE THREAD

**Issue by ArsThor** [0todd0000/spm1dmatlab#93]
Hi community

I would like to know how to manage 'NaN' while testing my results in an anova test. I explain myself. I have some EMG data that I would like to compare throught several conditions (4 conditions fo 13 subjects). For some trials, sometime the EMG was not workable, so I decided to replace the case by a NaN which make problem for the anova results.
Have a look:
On the Matrix:

0.0001    1.0000
    0.0002    1.0000
    0.0001    1.0000
    0.0002    1.0000
    0.0001    1.0000
    0.0003    1.0000
    0.0001    1.0000
    0.0001    1.0000
    0.0000    1.0000
    0.0002    1.0000
    0.0001    1.0000
    0.0001    1.0000
    0.0001    1.0000
    0.0001    2.0000
    0.0005    2.0000
    0.0001    2.0000
    0.0002    2.0000
    0.0000    2.0000
    0.0003    2.0000
    0.0001    2.0000
    0.0002    2.0000
    0.0001    2.0000
    0.0001    2.0000
    0.0000    2.0000
    0.0000    2.0000
    0.0001    2.0000
    0.0000    3.0000
    0.0000    3.0000
    0.0001    3.0000
    0.0001    3.0000
    0.0001    3.0000
    0.0002    3.0000
    0.0001    3.0000
       NaN    3.0000
    0.0000    3.0000
    0.0000    3.0000
    0.0000    3.0000
    0.0000    3.0000
    0.0000    3.0000
    0.0000    4.0000
    0.0001    4.0000
    0.0002    4.0000
    0.0001    4.0000
    0.0001    4.0000
    0.0003    4.0000
    0.0001    4.0000
    0.0003    4.0000
    0.0001    4.0000
    0.0001    4.0000
    0.0000    4.0000
    0.0001    4.0000
    0.0000    4.0000

On the results:

SPM{F} (0D) inference
      effect: 'Main A'
          SS: [NaN NaN]
          df: [3 48]
          MS: [NaN NaN]
           z: NaN
       alpha: 0.0500
       zstar: 2.7981
    h0reject: 0
           p: 1

I can't make a conclusion. If you already had this problem, you can save my life or rather my work.

Thank s a lot

ArsThor

**Comment by 0todd0000** [comment]
Dear ArsThor,

The current version of **spm1d** unfortunately does not support NaN handling. If an entire measurement had a problem, and it is replaced with NaN, then this is the classic case of missing data, and this case will be supported in future versions of **spm1d**.  If only part of a measurement is NaN then classical missing data procedures can't be followed (because 1D means and variances can't be estimated properly).  The only option in this case, as far as we are aware, is nonparametric inference, but we are not yet sure if this can be supported robustly across experimental designs, so it might not be supported in future versions of **spm1d**.

In order to deal with the problem we suggest one of the following:

1.  Remove all NaN measurements completely.

2.  Try to implement non-parametric inference. This can be done following this standalone script: 
./examples/nonparam/0d/ex_ttest_standalone.m
This script follows the procedures of Nichols & Holmes (2002).

Nichols TE, Holmes AP. Nonparametric permutation tests for functional neuroimaging: a primer with examples. Human brain mapping. 2002 Jan 1;15(1):1-25.

Todd
