### ISSUE TITLE
"participant effect" in a repeated measures ANOVA

### ISSUE THREAD

**Issue by NicolasFlores14** [0todd0000/spm1dmatlab#95]
Hello Todd,

I was wondering if it was possible to include a "participant effect" in a repeated measures ANOVA.
For example, in a two-way repeated measures ANOVA, I would like to investigate the interaction effect between the factor A and the factor B (the participants in this case). The code would be:
spmlist   = spm1d.stats.anova2rm(Y, A, B, SUBJ);

B=SUBJ, therefore, how can I test the participant effect without obtaining an error concerning an "unbalanced design" ?

Thank you for your help,
Best regards.

Nicolas

**Comment by 0todd0000** [comment]
Hi Nicolas,

No, it is not possible. If participants performed multiple tasks, then the design is repeated measures (RM) and explicit PARTICIPANT factor modeling is not possible.

Consider by analogy a paired t test, the simplest possible RM design. For participant "i" a single value "y_i" exists, representing the difference in that participant between the two conditions. The only possible way to model y_i is to use a single value "mu", representing the true mean difference across participants. In this scenario it is not possible to model PARTICIPANT, because PARTICIPANT differences are implicitly modeled in the true mean mu.  The same is true of all RM designs.

Todd
