### ISSUE TITLE
Post-hoc, two-way repeated measures ANOVA & effect sizes

### ISSUE THREAD

**Issue by andrashegyi** [0todd0000/spm1dmatlab#98]
Hi Todd,

Thank you for providing SPM for us. I have two questions and I have not found answer in previous posts.

I have a EMG data collected from 2 muscles at 3 different speeds of running. I have run a 2-way repeated measures ANOVA, where main effect of running speed and main effect of muscle is tested, as well as the interaction between running speed and muscle. I found no interaction and no main effect of muscle but main effect of speed was evident. Since there is no interaction and muscle effect, how should I pool the two muscles for post hoc analysis? I guess the currently available best option would be to run paired sample t-tests (with alpha level correction) but I am not sure how to do that because there is no interaction or muscle effect. Or should I run paired sample t-tests for each muscle to see the differences between speeds? I am not sure if it is easy to justify based on the ANOVA result, what do you think/suggest?

Another question. I previously calculated Cohen's d effect size for paired-sample t-test with 95%CI for paired-sample t-test:

ci0 = spm1d.stats.ci_pairedsample(yA, yB, 0.05, 'difference', 0);

C = zeros(1,101);
Sdiff = zeros(1,101);
SDyA = std(yA);
SDyB = std(yB);
MyA = mean(yA);
MyB = mean(yB);

for a = 1:101
    ca = corrcoef(yA(:,a),yB(:,a));
    C(a) = ca(2);
    Sdiff(a) = sqrt(SDyA(a)^2+SDyB(a)^2-2*C(a)*SDyA(a)*SDyB(a));
    CohenD(a) = (MyA(a)-MyB(a))/Sdiff(a);
end

CIL = ci0.ci(1,1:101)./Sdiff; % lower CI in raw values converted to standardized difference
CIU = ci0.ci(2,1:101)./Sdiff;
y = CohenD;
ye = abs(CIU-CIL)./2; % confidence limit

I hope this calculation is correct, can you please confirm? Looks good fro the figure at least because SPM(t) and Cohen's d overlap and they differ by sqrt(N).
For the current study I adjust my p threshold for multiple comparisons. To calculate confidence intervals, should I change the alpha level in this formula:
ci0 = spm1d.stats.ci_pairedsample(yA, yB, 0.05, 'difference', 0);

Thank you very much, in advance,
András

**Comment by 0todd0000** [comment]
Hi András,
Tough questions!

Post hoc:  paired t tests sound fine.  Another option is to combine the muscles into a single multivariate dependent variable and run a paired Hotelling's test. As long as the *post hoc* analyses are qualitatively consistent with the ANOVA results, and as long as you interpret only the ANOVA results as probabilistically valid (with the current version of **spm1d**), then anything should be fine. Robust, automated and probabilistically consistent *post hoc* analyses will be supported in a future release.

Cohen's effect size:
At first glance the calculations look fine. However, a slightly different denominator might be better, see:
https://www.real-statistics.com/students-t-distribution/paired-sample-t-test/cohens-d-paired-samples/
Regardless, please understand that the **spm1d** team can't check third-party code thoroughly in this forum because the code does not appear in **spm1d**.

Paired sample confidence intervals:
Since these are equivalent to paired t tests, the corrections from the *post hoc* paired tests should also be applied to the CIs.

Todd

**Comment by andrashegyi** [comment]
Hi,
Awesome, thank you for the quick and clear answer. 
The only reason I shared the code was that reviewers requested Cohen's d for my SPM comparisons and wanted to make sure that the same calculations apply for 1D as for 0D data. I believe your next release 0.5 will solve many similar issues. Thank you for your great work.
All the best,
András
