### ISSUE TITLE
Question regarding the need for an a priori power analysis and how to start

### ISSUE THREAD

**Issue by AndyArg** [0todd0000/spm1dmatlab#99]
Dear Todd,

I am conducting an experiment in which I will look into the effects a wearable orthesis might have on kinematics and muscle activity as well as on postural sway. As these effects are unknown prior to the experiment, especially in regard to possible significant effects on discrete parameters such as maxima and peaks, the use of spm makes a whole lot of sense as it is agnostic to specific areas in the continuum (not to mention its general advantage when it comes to 1D data). 
Nevertheless, an a priori power analysis for the estimation of necessary amount of test subjects and measurements should be mandatory (as you pointed out in your publication about power1d in 2017).

My Test-Design in slightly more detail:

1 Cohort of healthy test subjects will do 2 identical measurements with and without the orthesis in one configuration/setup and 2 measurements with and without the orthesis in another setup. Each measurement contains approx. 10-15 cyclic repetitions.
So my questions are:

1) How should I proceed with the necessary power analysis? Should I do some prior testings and use this to  generate multi-subject "pilot" data with power1d? 

2) Is it feasable to conduct a seperate spm analysis for every single parameter including kinematic data, emg and postural sway or do I have to combine these into a single coumputation to avoid multiple testing...? If so, I am not sure how to do that.

Any help would be highly appreciated, thank you!
Andy

**Comment by 0todd0000** [comment]
Hi Andy,

> 1. How should I proceed with the necessary power analysis? Should I do some prior testings and use this to  generate multi-subject "pilot" data with power1d?

The main steps are to (a) estimate expected variance, then (b) specify the effect that can justifiably regarded as "significant". For (a) pilot data is fine, but I also think approximate variance is fine, for example from published standard deviation values. (b) could also be from a pilot experiment, or from published effects, but it could also be a hypothesis-driven effect, derived from physics principles and/or from  musculoskeletal modeling results.

> 2. Is it feasable to conduct a seperate spm analysis for every single parameter including kinematic data, emg and postural sway or do I have to combine these into a single coumputation to avoid multiple testing...? If so, I am not sure how to do that.

This is a tough question. Yes, a correction for multiple corrections (MCs) should be employed when there are multiple variables, but as far as I know there is no appropriate procedure in biomechanics for doing this. The simplest correction is the Bonferroni correction, but this is almost certainly too conservative for biomechanical data, in which substantial correlation can exist between variables. Even more problematic is the fact that the current mechanical state generally affects the future state (e.g. larger-than-average forward-directed forces require subsequently larger-than-average rearward-directed forces in order to maintain constant forward-directed velocity). These mechanical constraints make the multiple corrections problem very complex in Biomechanics, and I don't think there is currently any proposed way to deal with this problem robustly. A robust solution would require at least a musculoskeletal model with which expected inter-variable covariance could be estimated. In lieu of that solution, I'd recommend using a Bonferroni correction to be conservative, and if you observe significance with a Bonferroni correction you'd also certainly observe it with a more appropriate, lower threshold.  Another option is to just state that it is an exploratory study, and that you wish to detect any existing effects with maximum sensitivity, so do not use a correction. However, in the exploratory case without corrections, it would also be important to mention that all of the findings would require verification in subsequent, independent experimentation. The main problem is that adding variables reduces the specificity and the power of the experiment, and the only robust solution that I'm aware of is to measure and test fewer variables.

Todd

**Comment by AndyArg** [comment]
Dear Todd,
thank you very much for your answer. 
Regards
Andy

**Comment by 0todd0000** [comment]
No problem!
